export const movies = [
  {
    id: 1,
    title: "The Shawshank Redemption",
    director: "Frank Darabont",
    authors: ["Stephen King"],
    year: 1994,
    genre: ["Drama"],
    rating: 9.3,
    duration: 142,
    language: "English",
    image: "https://image.tmdb.org/t/p/w500/q6y0Go1tsGEsmtFryDOJo3dEmqu.jpg",
    description:
      "Two imprisoned men bond over a number of years, finding solace and eventual redemption through acts of common decency.",
  },
  {
    id: 2,
    title: "The Godfather",
    director: "Francis Ford Coppola",
    authors: ["Mario Puzo"],
    year: 1972,
    genre: ["Crime", "Drama"],
    rating: 9.2,
    duration: 175,
    language: "English",
    image: "https://image.tmdb.org/t/p/w500/3bhkrj58Vtu7enYsLegHnDmni7A.jpg",
    description:
      "The aging patriarch of an organized crime dynasty transfers control to his reluctant son.",
  },
  {
    id: 3,
    title: "The Dark Knight",
    director: "Christopher Nolan",
    authors: ["Christopher Nolan", "Jonathan Nolan"],
    year: 2008,
    genre: ["Action", "Crime", "Drama"],
    rating: 9.0,
    duration: 152,
    language: "English",
    image: "https://image.tmdb.org/t/p/w500/qJ2tW6WMUDux911r6m7haRef0WH.jpg",
    description:
      "Batman raises the stakes in his war on crime with the help of Lt. Jim Gordon and DA Harvey Dent.",
  },
  {
    id: 4,
    title: "Pulp Fiction",
    director: "Quentin Tarantino",
    authors: ["Quentin Tarantino", "Roger Avary"],
    year: 1994,
    genre: ["Crime", "Drama"],
    rating: 8.9,
    duration: 154,
    language: "English",
    image: "https://image.tmdb.org/t/p/w500/d5iIlFn5s0ImszYzBPb8JPIfbXD.jpg",
    description:
      "The lives of two mob hitmen, a boxer, a gangster and his wife intertwine in four tales of violence and redemption.",
  },
  {
    id: 5,
    title: "Schindler's List",
    director: "Steven Spielberg",
    authors: ["Thomas Keneally", "Steven Zaillian"],
    year: 1993,
    genre: ["Biography", "Drama", "History"],
    rating: 9.0,
    duration: 195,
    language: "English",
    image: "https://image.tmdb.org/t/p/w500/sF1U4EUQS8YHUYjNl3pMGNIQyr0.jpg",
    description:
      "In German-occupied Poland during World War II, Oskar Schindler gradually becomes concerned for his Jewish workforce.",
  },
  {
    id: 6,
    title: "The Lord of the Rings: The Return of the King",
    director: "Peter Jackson",
    authors: ["J.R.R. Tolkien", "Fran Walsh"],
    year: 2003,
    genre: ["Action", "Adventure", "Drama"],
    rating: 9.0,
    duration: 201,
    language: "English",
    image: "https://image.tmdb.org/t/p/w500/rCzpDGLbOoPwLjy3OAm5NUPOTrC.jpg",
    description:
      "Gandalf and Aragorn lead the World of Men against Sauron's army to draw his gaze from Frodo and Sam.",
  },
  {
    id: 7,
    title: "The Good, the Bad and the Ugly",
    director: "Sergio Leone",
    authors: ["Agenore Incrocci", "Furio Scarpelli"],
    year: 1966,
    genre: ["Western"],
    rating: 8.8,
    duration: 178,
    language: "Italian",
    image: "https://image.tmdb.org/t/p/w500/bX2xnavhMYjWDoZp1VM6VnU1xwe.jpg",
    description:
      "A bounty hunting scam joins two men in an uneasy alliance against a third in a race to find a fortune in gold.",
  },
  {
    id: 8,
    title: "12 Angry Men",
    director: "Sidney Lumet",
    authors: ["Reginald Rose"],
    year: 1957,
    genre: ["Crime", "Drama"],
    rating: 9.0,
    duration: 96,
    language: "English",
    image: "https://image.tmdb.org/t/p/w500/ppd84D2i9W8jXmsyInGyihiSyqz.jpg",
    description:
      "A jury holdout attempts to prevent a miscarriage of justice by forcing his colleagues to reconsider the evidence.",
  },
  {
    id: 9,
    title: "Inception",
    director: "Christopher Nolan",
    authors: ["Christopher Nolan"],
    year: 2010,
    genre: ["Action", "Adventure", "Sci-Fi"],
    rating: 8.8,
    duration: 148,
    language: "English",
    image: "https://image.tmdb.org/t/p/w500/edv5CZvWj09upOsy2Y6IwDhK8bt.jpg",
    description:
      "A thief who steals corporate secrets through dream-sharing technology is given the inverse task of planting an idea.",
  },
  {
    id: 10,
    title: "Fight Club",
    director: "David Fincher",
    authors: ["Chuck Palahniuk", "Jim Uhls"],
    year: 1999,
    genre: ["Drama"],
    rating: 8.8,
    duration: 139,
    language: "English",
    image: "https://image.tmdb.org/t/p/w500/pB8BM7pdSp6B6Ih7QZ4DrQ3PmJK.jpg",
    description:
      "An insomniac office worker and a devil-may-care soapmaker form an underground fight club.",
  },
  {
    id: 11,
    title: "Forrest Gump",
    director: "Robert Zemeckis",
    authors: ["Winston Groom", "Eric Roth"],
    year: 1994,
    genre: ["Drama", "Romance"],
    rating: 8.8,
    duration: 142,
    language: "English",
    image: "https://image.tmdb.org/t/p/w500/arw2vcBveWOVZr6pxd9XTd1TdQa.jpg",
    description:
      "The presidencies of Kennedy and Johnson, the Vietnam War, and other historical events unfold through the perspective of an Alabama man.",
  },
  {
    id: 12,
    title: "Goodfellas",
    director: "Martin Scorsese",
    authors: ["Nicholas Pileggi", "Martin Scorsese"],
    year: 1990,
    genre: ["Biography", "Crime", "Drama"],
    rating: 8.7,
    duration: 146,
    language: "English",
    image: "https://image.tmdb.org/t/p/w500/aKuFiU82s5ISJpGZp7YkIr3kCUd.jpg",
    description:
      "The story of Henry Hill and his life in the mob, covering his relationship with his wife Karen Hill and his mob partners.",
  },
  {
    id: 13,
    title: "The Matrix",
    director: "Lana Wachowski",
    authors: ["Lana Wachowski", "Lilly Wachowski"],
    year: 1999,
    genre: ["Action", "Sci-Fi"],
    rating: 8.7,
    duration: 136,
    language: "English",
    image: "https://image.tmdb.org/t/p/w500/f89U3ADr1oiB1s9GkdPOEpXUk5H.jpg",
    description:
      "A computer hacker learns from mysterious rebels about the true nature of his reality and his role in the war against its controllers.",
  },
  {
    id: 14,
    title: "Star Wars: Episode V – The Empire Strikes Back",
    director: "Irvin Kershner",
    authors: ["Leigh Brackett", "Lawrence Kasdan"],
    year: 1980,
    genre: ["Action", "Adventure", "Fantasy"],
    rating: 8.7,
    duration: 124,
    language: "English",
    image: "https://image.tmdb.org/t/p/w500/2l05cFWJacyIsTpsqSgH0wQXe4V.jpg",
    description:
      "After the Rebels are overpowered by the Empire, Luke Skywalker begins his Jedi training with Master Yoda.",
  },
  {
    id: 15,
    title: "One Flew Over the Cuckoo's Nest",
    director: "Miloš Forman",
    authors: ["Ken Kesey", "Lawrence Hauben"],
    year: 1975,
    genre: ["Drama"],
    rating: 8.7,
    duration: 133,
    language: "English",
    image: "https://image.tmdb.org/t/p/w500/3jcbDmRFiQ83drXNOvRDeKHxS0C.jpg",
    description:
      "A criminal pleads insanity and is admitted to a mental institution, where he rebels against the oppressive nurse.",
  },
  {
    id: 16,
    title: "Interstellar",
    director: "Christopher Nolan",
    authors: ["Jonathan Nolan", "Christopher Nolan"],
    year: 2014,
    genre: ["Adventure", "Drama", "Sci-Fi"],
    rating: 8.6,
    duration: 169,
    language: "English",
    image: "https://image.tmdb.org/t/p/w500/gEU2QniE6E77NI6lCU6MxlNBvIx.jpg",
    description:
      "A team of explorers travel through a wormhole in space in an attempt to ensure humanity's survival.",
  },
  {
    id: 17,
    title: "Gladiator",
    director: "Ridley Scott",
    authors: ["David Franzoni", "John Logan"],
    year: 2000,
    genre: ["Action", "Adventure", "Drama"],
    rating: 8.5,
    duration: 155,
    language: "English",
    image: "https://image.tmdb.org/t/p/w500/ty8TGRuvJLPUmAR1H1nRIsgwvim.jpg",
    description:
      "A former Roman General sets out to exact vengeance against the corrupt emperor who murdered his family.",
  },
  {
    id: 18,
    title: "Parasite",
    director: "Bong Joon-ho",
    authors: ["Bong Joon-ho", "Han Jin-won"],
    year: 2019,
    genre: ["Comedy", "Drama", "Thriller"],
    rating: 8.5,
    duration: 132,
    language: "Korean",
    image: "https://image.tmdb.org/t/p/w500/7IiTTgloJzvGI1TAYymCfbfl3vT.jpg",
    description:
      "Greed and class discrimination threaten the newly formed symbiotic relationship between the wealthy Park family and the destitute Kim clan.",
  },
  {
    id: 19,
    title: "Joker",
    director: "Todd Phillips",
    authors: ["Todd Phillips", "Scott Silver"],
    year: 2019,
    genre: ["Crime", "Drama", "Thriller"],
    rating: 8.4,
    duration: 122,
    language: "English",
    image: "https://image.tmdb.org/t/p/w500/udDclJoHjfjb8Ekgsd4FDteOkCU.jpg",
    description:
      "In Gotham City, mentally troubled comedian Arthur Fleck embarks on a downward spiral of revolution and bloody crime.",
  },
  {
    id: 20,
    title: "Whiplash",
    director: "Damien Chazelle",
    authors: ["Damien Chazelle"],
    year: 2014,
    genre: ["Drama", "Music"],
    rating: 8.5,
    duration: 107,
    language: "English",
    image: "https://image.tmdb.org/t/p/w500/7fn624j5lj3xTme2SgiLCeuedmO.jpg",
    description:
      "A promising young drummer enrolls at a cut-throat music conservatory where his dreams of greatness are tested by a relentless instructor.",
  },
  {
    id: 21,
    title: "The Silence of the Lambs",
    director: "Jonathan Demme",
    authors: ["Thomas Harris", "Ted Tally"],
    year: 1991,
    genre: ["Crime", "Drama", "Thriller"],
    rating: 8.6,
    duration: 118,
    language: "English",
    image: "https://image.tmdb.org/t/p/w500/uS9m8OBk1A8eM9I042bx8XXpqAq.jpg",
    description:
      "A young F.B.I. cadet must receive the help of an incarcerated and manipulative cannibal killer to help catch another serial killer.",
  },
  {
    id: 22,
    title: "Saving Private Ryan",
    director: "Steven Spielberg",
    authors: ["Robert Rodat"],
    year: 1998,
    genre: ["Drama", "War"],
    rating: 8.6,
    duration: 169,
    language: "English",
    image: "https://image.tmdb.org/t/p/w500/1wY4psJ5NVEhCuOYROwLH2XExM2.jpg",
    description:
      "Following the Normandy Landings, a group of U.S. soldiers go behind enemy lines to retrieve a paratrooper whose brothers have been killed.",
  },
  {
    id: 23,
    title: "City of God",
    director: "Fernando Meirelles",
    authors: ["Paulo Lins", "Bráulio Mantovani"],
    year: 2002,
    genre: ["Crime", "Drama"],
    rating: 8.6,
    duration: 130,
    language: "Portuguese",
    image: "https://image.tmdb.org/t/p/w500/k7eYdWvhYQyRQoU2TB2A2Xu2grZ.jpg",
    description:
      "In the slums of Rio, two kids' paths diverge as one becomes a photographer and the other a drug dealer.",
  },
  {
    id: 24,
    title: "Life is Beautiful",
    director: "Roberto Benigni",
    authors: ["Vincenzo Cerami", "Roberto Benigni"],
    year: 1997,
    genre: ["Comedy", "Drama", "Romance"],
    rating: 8.6,
    duration: 116,
    language: "Italian",
    image: "https://image.tmdb.org/t/p/w500/74hLDKjD5aGYOotO6esUVaeISa2.jpg",
    description:
      "When a Jewish waiter and his son become victims of the Holocaust, he uses humor and imagination to protect his son from the dangers around their camp.",
  },
  {
    id: 25,
    title: "The Pianist",
    director: "Roman Polanski",
    authors: ["Władysław Szpilman", "Ronald Harwood"],
    year: 2002,
    genre: ["Biography", "Drama", "Music"],
    rating: 8.5,
    duration: 150,
    language: "English",
    image: "https://image.tmdb.org/t/p/w500/2hFvxCCWrTmCYwfy7yum0GKRi3Y.jpg",
    description:
      "A Polish Jewish musician struggles to survive the destruction of the Warsaw ghetto during World War II.",
  },
  {
    id: 26,
    title: "Spirited Away",
    director: "Hayao Miyazaki",
    authors: ["Hayao Miyazaki"],
    year: 2001,
    genre: ["Animation", "Adventure", "Family"],
    rating: 8.6,
    duration: 125,
    language: "Japanese",
    image: "https://image.tmdb.org/t/p/w500/39wmItIWsg5sZMyRUHLkWBcuVCM.jpg",
    description:
      "During her family's move to the suburbs, a sullen 10-year-old girl wanders into a world ruled by gods, witches, and spirits.",
  },
  {
    id: 27,
    title: "The Lion King",
    director: "Roger Allers",
    authors: ["Irene Mecchi", "Jonathan Roberts"],
    year: 1994,
    genre: ["Animation", "Adventure", "Drama"],
    rating: 8.5,
    duration: 88,
    language: "English",
    image: "https://image.tmdb.org/t/p/w500/sKCr78MXSLixwmZ8DyJLrpMsd15.jpg",
    description:
      "Lion prince Simba and his father are targeted by his bitter uncle, who wants to ascend the throne himself.",
  },
  {
    id: 28,
    title: "Back to the Future",
    director: "Robert Zemeckis",
    authors: ["Robert Zemeckis", "Bob Gale"],
    year: 1985,
    genre: ["Adventure", "Comedy", "Sci-Fi"],
    rating: 8.5,
    duration: 116,
    language: "English",
    image: "https://image.tmdb.org/t/p/w500/fNOH9f1aA7XRTzl1sAOx9iF553Q.jpg",
    description:
      "Marty McFly, a 17-year-old high school student, is accidentally sent 30 years into the past in a time-traveling DeLorean.",
  },
  {
    id: 29,
    title: "Alien",
    director: "Ridley Scott",
    authors: ["Dan O'Bannon", "Ronald Shusett"],
    year: 1979,
    genre: ["Horror", "Sci-Fi"],
    rating: 8.4,
    duration: 117,
    language: "English",
    image: "https://image.tmdb.org/t/p/w500/vfrQk5IPloGg1v9Rzbh2Eg3VGyM.jpg",
    description:
      "The crew of a commercial spacecraft encounters a deadly extraterrestrial creature after investigating an unknown transmission.",
  },
  {
    id: 30,
    title: "Avengers: Endgame",
    director: "Anthony Russo",
    authors: ["Christopher Markus", "Stephen McFeely"],
    year: 2019,
    genre: ["Action", "Adventure", "Drama"],
    rating: 8.4,
    duration: 181,
    language: "English",
    image: "https://image.tmdb.org/t/p/w500/or06FN3Dka5tukK1e9sl16pB3iy.jpg",
    description:
      "With the universe in ruins, the Avengers assemble once more to reverse Thanos' actions.",
  },
  {
    id: 31,
    title: "WALL·E",
    director: "Andrew Stanton",
    authors: ["Andrew Stanton", "Pete Docter"],
    year: 2008,
    genre: ["Animation", "Adventure", "Family"],
    rating: 8.4,
    duration: 98,
    language: "English",
    image: "https://image.tmdb.org/t/p/w500/hbhFnRzzg6ZDmm8YAmxBnQpQIPh.jpg",
    description:
      "In the distant future, a small waste-collecting robot inadvertently embarks on a space journey that will decide the fate of mankind.",
  },
  {
    id: 32,
    title: "The Departed",
    director: "Martin Scorsese",
    authors: ["William Monahan"],
    year: 2006,
    genre: ["Crime", "Drama", "Thriller"],
    rating: 8.5,
    duration: 151,
    language: "English",
    image: "https://image.tmdb.org/t/p/w500/nT97ifVT2J1yMQmeq20Qblg61T.jpg",
    description:
      "An undercover cop and a mole in the police attempt to identify each other while infiltrating an Irish gang in South Boston.",
  },
  {
    id: 33,
    title: "Eternal Sunshine of the Spotless Mind",
    director: "Michel Gondry",
    authors: ["Charlie Kaufman"],
    year: 2004,
    genre: ["Drama", "Romance", "Sci-Fi"],
    rating: 8.3,
    duration: 108,
    language: "English",
    image: "https://image.tmdb.org/t/p/w500/5MwkWH9tYHv3mV9OdYTMR5qreIz.jpg",
    description:
      "When their relationship turns sour, a couple undergoes a medical procedure to have each other erased from their memories.",
  },
  {
    id: 34,
    title: "Memento",
    director: "Christopher Nolan",
    authors: ["Jonathan Nolan", "Christopher Nolan"],
    year: 2000,
    genre: ["Mystery", "Thriller"],
    rating: 8.4,
    duration: 113,
    language: "English",
    image: "https://image.tmdb.org/t/p/w500/yuNs09hvpHVU1cBTCAk9zxsL2oW.jpg",
    description:
      "A man with short-term memory loss attempts to track down his wife's murderer.",
  },
  {
    id: 35,
    title: "Apocalypse Now",
    director: "Francis Ford Coppola",
    authors: ["John Milius", "Francis Ford Coppola"],
    year: 1979,
    genre: ["Drama", "Mystery", "War"],
    rating: 8.4,
    duration: 147,
    language: "English",
    image: "https://image.tmdb.org/t/p/w500/gQB8Y5RCMkv2zwzFHbUJX3kAhvA.jpg",
    description:
      "A U.S. Army officer serving in Vietnam is tasked with assassinating a renegade Special Forces Colonel.",
  },
  {
    id: 36,
    title: "Toy Story",
    director: "John Lasseter",
    authors: ["John Lasseter", "Pete Docter"],
    year: 1995,
    genre: ["Animation", "Adventure", "Comedy"],
    rating: 8.3,
    duration: 81,
    language: "English",
    image: "https://image.tmdb.org/t/p/w500/uXDfjJbdP4ijW5hWSBrPl9KaI82.jpg",
    description:
      "A cowboy doll is profoundly threatened when a new spaceman figure supplants him as top toy in a boy's room.",
  },
  {
    id: 37,
    title: "Django Unchained",
    director: "Quentin Tarantino",
    authors: ["Quentin Tarantino"],
    year: 2012,
    genre: ["Drama", "Western"],
    rating: 8.4,
    duration: 165,
    language: "English",
    image: "https://image.tmdb.org/t/p/w500/7oWY8VDWW7thTzWspqizvw5VFZH.jpg",
    description:
      "With the help of a German bounty hunter, a freed Django sets out to rescue his wife from a brutal Mississippi plantation owner.",
  },
  {
    id: 38,
    title: "Braveheart",
    director: "Mel Gibson",
    authors: ["Randall Wallace"],
    year: 1995,
    genre: ["Biography", "Drama", "History"],
    rating: 8.3,
    duration: 178,
    language: "English",
    image: "https://image.tmdb.org/t/p/w500/or1gBugydmjToAEq7OZY0owwFk.jpg",
    description:
      "Scottish warrior William Wallace leads his countrymen in a rebellion to free his homeland from the tyranny of King Edward I of England.",
  },
  {
    id: 39,
    title: "The Prestige",
    director: "Christopher Nolan",
    authors: ["Christopher Priest", "Jonathan Nolan"],
    year: 2006,
    genre: ["Drama", "Mystery", "Sci-Fi"],
    rating: 8.5,
    duration: 130,
    language: "English",
    image: "https://image.tmdb.org/t/p/w500/5MXyQfz8xUP3dIFPTubhTsbFY6N.jpg",
    description:
      "After a tragic accident, two stage magicians engage in a battle to create the ultimate illusion while sacrificing everything they have.",
  },
  {
    id: 40,
    title: "American History X",
    director: "Tony Kaye",
    authors: ["David McKenna"],
    year: 1998,
    genre: ["Drama"],
    rating: 8.5,
    duration: 119,
    language: "English",
    image: "https://image.tmdb.org/t/p/w500/396tdvsOWHhWl76LIBhJz2golX5.jpg",
    description:
      "A former neo-nazi skinhead tries to prevent his younger brother from going down the same wrong path that he did.",
  },
  {
    id: 41,
    title: "The Truman Show",
    director: "Peter Weir",
    authors: ["Andrew Niccol"],
    year: 1998,
    genre: ["Comedy", "Drama"],
    rating: 8.2,
    duration: 103,
    language: "English",
    image: "https://image.tmdb.org/t/p/w500/vuza0WqY239yBXOadKlGwJsZJFE.jpg",
    description:
      "An insurance salesman discovers his whole life is actually a reality TV show.",
  },
  {
    id: 42,
    title: "Coco",
    director: "Lee Unkrich",
    authors: ["Lee Unkrich", "Adrian Molina"],
    year: 2017,
    genre: ["Animation", "Adventure", "Comedy"],
    rating: 8.4,
    duration: 105,
    language: "English",
    image: "https://image.tmdb.org/t/p/w500/gGEsBPAijhVUFoiNpgZXqRVWJt2.jpg",
    description:
      "Aspiring musician Miguel enters the Land of the Dead to find his great-great-grandfather and lift his family's ban on music.",
  },
  {
    id: 43,
    title: "Casablanca",
    director: "Michael Curtiz",
    authors: ["Julius J. Epstein", "Philip G. Epstein"],
    year: 1942,
    genre: ["Drama", "Romance", "War"],
    rating: 8.5,
    duration: 102,
    language: "English",
    image: "https://image.tmdb.org/t/p/w500/5K7cOHoay2mZusSLezBOY0Qxh8a.jpg",
    description:
      "A cynical expatriate American cafe owner struggles to decide whether to help his former lover and her fugitive husband escape the Nazis.",
  },
  {
    id: 44,
    title: "Titanic",
    director: "James Cameron",
    authors: ["James Cameron"],
    year: 1997,
    genre: ["Drama", "Romance"],
    rating: 7.9,
    duration: 194,
    language: "English",
    image: "https://image.tmdb.org/t/p/w500/9xjZS2rlVxm8SFx8kPC3aIGCOYQ.jpg",
    description:
      "A seventeen-year-old aristocrat falls in love with a poor artist aboard the luxurious, ill-fated R.M.S. Titanic.",
  },
  {
    id: 45,
    title: "The Shining",
    director: "Stanley Kubrick",
    authors: ["Stephen King", "Stanley Kubrick"],
    year: 1980,
    genre: ["Drama", "Horror"],
    rating: 8.4,
    duration: 146,
    language: "English",
    image: "https://image.tmdb.org/t/p/w500/b6ko0IKC8MdYBBPkkA1aBPLe2yz.jpg",
    description:
      "A family heads to an isolated hotel for the winter where a sinister presence influences the father into violence.",
  },
  {
    id: 46,
    title: "2001: A Space Odyssey",
    director: "Stanley Kubrick",
    authors: ["Stanley Kubrick", "Arthur C. Clarke"],
    year: 1968,
    genre: ["Adventure", "Sci-Fi"],
    rating: 8.3,
    duration: 149,
    language: "English",
    image: "https://image.tmdb.org/t/p/w500/ve72VxNqjGM69Uky4WTo2bK6rfq.jpg",
    description:
      "After discovering a mysterious artifact buried beneath the Lunar surface, mankind sets off on a quest to find its origins.",
  },
  {
    id: 47,
    title: "Blade Runner 2049",
    director: "Denis Villeneuve",
    authors: ["Hampton Fancher", "Michael Green"],
    year: 2017,
    genre: ["Drama", "Mystery", "Sci-Fi"],
    rating: 8.0,
    duration: 164,
    language: "English",
    image: "https://image.tmdb.org/t/p/w500/gajva2L0rPYkEWjzgFlBXCAVBE5.jpg",
    description:
      "Young Blade Runner K's discovery of a long-buried secret leads him to track down former Blade Runner Rick Deckard.",
  },
  {
    id: 48,
    title: "Mad Max: Fury Road",
    director: "George Miller",
    authors: ["George Miller", "Brendan McCarthy"],
    year: 2015,
    genre: ["Action", "Adventure", "Sci-Fi"],
    rating: 8.1,
    duration: 120,
    language: "English",
    image: "https://image.tmdb.org/t/p/w500/hA2ple9q4qnwxp3hKVNhroipsir.jpg",
    description:
      "In a post-apocalyptic wasteland, a woman rebels against a tyrannical ruler in search for her homeland.",
  },
  {
    id: 49,
    title: "No Country for Old Men",
    director: "Joel Coen",
    authors: ["Cormac McCarthy", "Ethan Coen"],
    year: 2007,
    genre: ["Crime", "Drama", "Thriller"],
    rating: 8.2,
    duration: 122,
    language: "English",
    image: "https://image.tmdb.org/t/p/w500/6d5XOczc0bEBgvSfHMdSBOJpgTh.jpg",
    description:
      "Violence and mayhem ensue after a hunter stumbles upon a drug deal gone wrong and more than two million dollars in cash near the Rio Grande.",
  },
  {
    id: 50,
    title: "Amélie",
    director: "Jean-Pierre Jeunet",
    authors: ["Guillaume Laurant", "Jean-Pierre Jeunet"],
    year: 2001,
    genre: ["Comedy", "Romance"],
    rating: 8.3,
    duration: 122,
    language: "French",
    image: "https://image.tmdb.org/t/p/w500/fy0wBnFs39vHQZImNi48lr1PKBL.jpg",
    description:
      "An innocent and naive Parisian woman decides to help those around her and along the way discovers love.",
  },
  {
    id: 51,
    title: "The Wolf of Wall Street",
    director: "Martin Scorsese",
    authors: ["Jordan Belfort", "Terence Winter"],
    year: 2013,
    genre: ["Biography", "Comedy", "Crime"],
    rating: 8.2,
    duration: 180,
    language: "English",
    image: "https://image.tmdb.org/t/p/w500/34m2tygAYBGqA9MXKhRDtzYd4Ao.jpg",
    description:
      "Based on the true story of Jordan Belfort, from his rise as a wealthy stockbroker to his fall involving crime, corruption and the federal government.",
  },
  {
    id: 52,
    title: "Requiem for a Dream",
    director: "Darren Aronofsky",
    authors: ["Hubert Selby Jr.", "Darren Aronofsky"],
    year: 2000,
    genre: ["Drama"],
    rating: 8.3,
    duration: 102,
    language: "English",
    image: "https://image.tmdb.org/t/p/w500/nOd6vjEmzCT0k4VYqsA2hwyi87C.jpg",
    description:
      "The drug-induced utopias of four Coney Island people are shattered when their addictions run deep.",
  },
  {
    id: 53,
    title: "A Beautiful Mind",
    director: "Ron Howard",
    authors: ["Sylvia Nasar", "Akiva Goldsman"],
    year: 2001,
    genre: ["Biography", "Drama"],
    rating: 8.2,
    duration: 135,
    language: "English",
    image: "https://image.tmdb.org/t/p/w500/zwzWCmH72OSC9NA0ipoqynmkVRS.jpg",
    description:
      "After John Nash accepts secret work in cryptography, his life takes a turn for the nightmarish.",
  },
  {
    id: 54,
    title: "The Grand Budapest Hotel",
    director: "Wes Anderson",
    authors: ["Wes Anderson", "Hugo Guinness"],
    year: 2014,
    genre: ["Adventure", "Comedy", "Crime"],
    rating: 8.1,
    duration: 99,
    language: "English",
    image: "https://image.tmdb.org/t/p/w500/eWdyYQreja6JGCzqHWXpWHDrrPo.jpg",
    description:
      "A writer encounters the owner of an aging high-class hotel, who tells him of his early years serving as a lobby boy under an exceptional concierge.",
  },
  {
    id: 55,
    title: "Oldboy",
    director: "Park Chan-wook",
    authors: ["Garon Tsuchiya", "Park Chan-wook"],
    year: 2003,
    genre: ["Action", "Drama", "Mystery"],
    rating: 8.4,
    duration: 120,
    language: "Korean",
    image: "https://image.tmdb.org/t/p/w500/pWDtjs568ZfOTMW2vZGAVjFiDzm.jpg",
    description:
      "After being inexplicably imprisoned for 15 years, Oh Dae-su is released and must find his captor in five days.",
  },
  {
    id: 56,
    title: "The Big Lebowski",
    director: "Joel Coen",
    authors: ["Ethan Coen", "Joel Coen"],
    year: 1998,
    genre: ["Comedy", "Crime"],
    rating: 8.1,
    duration: 117,
    language: "English",
    image: "https://image.tmdb.org/t/p/w500/d3iJlAi2RwKNqeAYQSHnXsWNmTT.jpg",
    description:
      "Ultimate L.A. slacker Jeff Lebowski, mistaken for a millionaire, seeks restitution for his ruined rug and enlists his bowling buddies.",
  },
  {
    id: 57,
    title: "Pan's Labyrinth",
    director: "Guillermo del Toro",
    authors: ["Guillermo del Toro"],
    year: 2006,
    genre: ["Drama", "Fantasy", "War"],
    rating: 8.2,
    duration: 118,
    language: "Spanish",
    image: "https://image.tmdb.org/t/p/w500/htykzD59wGaTHxSGpPfcGOWpjQ3.jpg",
    description:
      "In the Falangist Spain of 1944, the bookish young stepdaughter of a sadistic army officer escapes into an eerie fantasy world.",
  },
  {
    id: 58,
    title: "Heat",
    director: "Michael Mann",
    authors: ["Michael Mann"],
    year: 1995,
    genre: ["Action", "Crime", "Drama"],
    rating: 8.3,
    duration: 170,
    language: "English",
    image: "https://image.tmdb.org/t/p/w500/zNFSuSKtHAfFkEjcEu1kwvzKBM5.jpg",
    description:
      "A group of professional bank robbers start to feel the heat from police when they unknowingly leave a clue at their latest heist.",
  },
  {
    id: 59,
    title: "The Seventh Seal",
    director: "Ingmar Bergman",
    authors: ["Ingmar Bergman"],
    year: 1957,
    genre: ["Drama", "Fantasy"],
    rating: 8.1,
    duration: 96,
    language: "Swedish",
    image: "https://image.tmdb.org/t/p/w500/LlMzPr6bpLVfM0IT7qvFbYRbXg.jpg",
    description:
      "A medieval knight returning from the Crusades seeks answers about life, death, and God as he plays chess against the Grim Reaper.",
  },
  {
    id: 60,
    title: "There Will Be Blood",
    director: "Paul Thomas Anderson",
    authors: ["Upton Sinclair", "Paul Thomas Anderson"],
    year: 2007,
    genre: ["Drama", "History", "Western"],
    rating: 8.2,
    duration: 158,
    language: "English",
    image: "https://image.tmdb.org/t/p/w500/fa0RDkAlCec0STeMNAhPaF89q6U.jpg",
    description:
      "A story of family, religion, hatred, oil and madness, focusing on a turn-of-the-century prospector in the early days of the oil business.",
  },
  {
    id: 61,
    title: "Get Out",
    director: "Jordan Peele",
    authors: ["Jordan Peele"],
    year: 2017,
    genre: ["Horror", "Mystery", "Thriller"],
    rating: 7.7,
    duration: 104,
    language: "English",
    image: "https://image.tmdb.org/t/p/w500/tFXcEccSQMf3lfhfXKSU9iRBpa3.jpg",
    description:
      "A young African-American visits his white girlfriend's parents for the weekend, where his uneasiness eventually reaches a boiling point.",
  },
  {
    id: 62,
    title: "Dunkirk",
    director: "Christopher Nolan",
    authors: ["Christopher Nolan"],
    year: 2017,
    genre: ["Action", "Drama", "History"],
    rating: 7.9,
    duration: 106,
    language: "English",
    image: "https://image.tmdb.org/t/p/w500/ebSnODDg9lbsMIaWg2uAbjn7TO5.jpg",
    description:
      "Allied soldiers are surrounded by the German Army and evacuated during a fierce battle in World War II.",
  },
  {
    id: 63,
    title: "La La Land",
    director: "Damien Chazelle",
    authors: ["Damien Chazelle"],
    year: 2016,
    genre: ["Comedy", "Drama", "Music"],
    rating: 8.0,
    duration: 128,
    language: "English",
    image: "https://image.tmdb.org/t/p/w500/uDO8zWDhfWwoFdKS4fzkUJt0Rf0.jpg",
    description:
      "While navigating their careers in Los Angeles, a pianist and an actress fall in love while attempting to reconcile their aspirations.",
  },
  {
    id: 64,
    title: "The Green Mile",
    director: "Frank Darabont",
    authors: ["Stephen King", "Frank Darabont"],
    year: 1999,
    genre: ["Crime", "Drama", "Fantasy"],
    rating: 8.6,
    duration: 189,
    language: "English",
    image: "https://image.tmdb.org/t/p/w500/velWPhVMQeQKcxggNEU8YmIo52R.jpg",
    description:
      "The lives of guards on Death Row are affected by one of their charges: a gentle giant who possesses the gift of healing.",
  },
  {
    id: 65,
    title: "A Clockwork Orange",
    director: "Stanley Kubrick",
    authors: ["Anthony Burgess", "Stanley Kubrick"],
    year: 1971,
    genre: ["Crime", "Drama", "Sci-Fi"],
    rating: 8.3,
    duration: 136,
    language: "English",
    image: "https://image.tmdb.org/t/p/w500/4sHeTAp65WrSSuc05XdwZATKLBq.jpg",
    description:
      "In the future, a sadistic gang leader is imprisoned and volunteers for a conduct-aversion experiment that doesn't go as planned.",
  },
  {
    id: 66,
    title: "Jurassic Park",
    director: "Steven Spielberg",
    authors: ["Michael Crichton", "David Koepp"],
    year: 1993,
    genre: ["Action", "Adventure", "Sci-Fi"],
    rating: 8.1,
    duration: 127,
    language: "English",
    image: "https://image.tmdb.org/t/p/w500/oU7Oq2kFAAlGqoX67VHPnb4wIBV.jpg",
    description:
      "A pragmatic paleontologist is tasked with protecting kids after a power failure causes a theme park's cloned dinosaurs to run loose.",
  },
  {
    id: 67,
    title: "Hacksaw Ridge",
    director: "Mel Gibson",
    authors: ["Robert Schenkkan", "Andrew Knight"],
    year: 2016,
    genre: ["Biography", "Drama", "History"],
    rating: 8.1,
    duration: 131,
    language: "English",
    image: "https://image.tmdb.org/t/p/w500/aTn7g5HaTTCMlJPvaJaIr5biMkq.jpg",
    description:
      "WWII Army Medic Desmond T. Doss refuses to kill people and becomes the first American to receive the Medal of Honor without firing a shot.",
  },
  {
    id: 68,
    title: "Inglourious Basterds",
    director: "Quentin Tarantino",
    authors: ["Quentin Tarantino"],
    year: 2009,
    genre: ["Adventure", "Drama", "War"],
    rating: 8.3,
    duration: 153,
    language: "English",
    image: "https://image.tmdb.org/t/p/w500/7sfbEnaARXDDhKm0CZ7D7uc2sbo.jpg",
    description:
      "In Nazi-occupied France, a plan to assassinate Nazi leaders by Jewish U.S. soldiers coincides with a theatre owner's own vengeful plans.",
  },
  {
    id: 69,
    title: "The Revenant",
    director: "Alejandro G. Iñárritu",
    authors: ["Michael Punke", "Mark L. Smith"],
    year: 2015,
    genre: ["Action", "Adventure", "Drama"],
    rating: 8.0,
    duration: 156,
    language: "English",
    image: "https://image.tmdb.org/t/p/w500/ji3ecJphATlVgWNY0B0RVXZizdt.jpg",
    description:
      "A frontiersman on a fur trading expedition in the 1820s fights for survival after being mauled by a bear.",
  },
  {
    id: 70,
    title: "District 9",
    director: "Neill Blomkamp",
    authors: ["Neill Blomkamp", "Terri Tatchell"],
    year: 2009,
    genre: ["Action", "Sci-Fi", "Thriller"],
    rating: 7.9,
    duration: 112,
    language: "English",
    image: "https://image.tmdb.org/t/p/w500/tuGLQlJQ3yWFmEBLLLKPwOSblIA.jpg",
    description:
      "An extraterrestrial race forced to live in slum-like conditions on Earth finds a kindred spirit in a government agent exposed to their biotechnology.",
  },
  {
    id: 71,
    title: "The Social Network",
    director: "David Fincher",
    authors: ["Ben Mezrich", "Aaron Sorkin"],
    year: 2010,
    genre: ["Biography", "Drama"],
    rating: 7.8,
    duration: 120,
    language: "English",
    image: "https://image.tmdb.org/t/p/w500/n0ybibhJtQ5icDqTp8eRytcIHJx.jpg",
    description:
      "As Harvard student Mark Zuckerberg creates Facebook, he is sued by the twins who claimed he stole their idea.",
  },
  {
    id: 72,
    title: "1917",
    director: "Sam Mendes",
    authors: ["Sam Mendes", "Krysty Wilson-Cairns"],
    year: 2019,
    genre: ["Drama", "War"],
    rating: 8.3,
    duration: 119,
    language: "English",
    image: "https://image.tmdb.org/t/p/w500/iZf0KyrE25z1sage4SYQLnzAFIo.jpg",
    description:
      "Two soldiers race against time to deliver a message that will stop 1,600 men from walking straight into a deadly ambush.",
  },
  {
    id: 73,
    title: "The Dark Knight Rises",
    director: "Christopher Nolan",
    authors: ["Christopher Nolan", "Jonathan Nolan"],
    year: 2012,
    genre: ["Action", "Adventure"],
    rating: 8.4,
    duration: 164,
    language: "English",
    image: "https://image.tmdb.org/t/p/w500/85cWkCVfDGcCxPOEnz9502jBEHQ.jpg",
    description:
      "Eight years after the Joker's reign of anarchy, Batman must return to defend Gotham City against jewel thief Selina Kyle and mercenary Bane.",
  },
  {
    id: 74,
    title: "Princess Mononoke",
    director: "Hayao Miyazaki",
    authors: ["Hayao Miyazaki"],
    year: 1997,
    genre: ["Animation", "Action", "Adventure"],
    rating: 8.4,
    duration: 134,
    language: "Japanese",
    image: "https://image.tmdb.org/t/p/w500/rGmOrOKFo9OQZU3XsIItLCAGn5p.jpg",
    description:
      "On a journey to cure a curse, Ashitaka finds himself in the middle of a war between forest gods and a mining colony.",
  },
  {
    id: 75,
    title: "Leon: The Professional",
    director: "Luc Besson",
    authors: ["Luc Besson"],
    year: 1994,
    genre: ["Action", "Crime", "Drama"],
    rating: 8.5,
    duration: 110,
    language: "English",
    image: "https://image.tmdb.org/t/p/w500/yI6X2cCM5YPJtxMhUd3dPGqDAhw.jpg",
    description:
      "12-year-old Mathilda is reluctantly taken in by Léon, a professional assassin, after her family is murdered.",
  },
  {
    id: 76,
    title: "Psycho",
    director: "Alfred Hitchcock",
    authors: ["Robert Bloch", "Joseph Stefano"],
    year: 1960,
    genre: ["Horror", "Mystery", "Thriller"],
    rating: 8.5,
    duration: 109,
    language: "English",
    image: "https://image.tmdb.org/t/p/w500/yz4QVqPx3h1hD1DfqqQkCq3rmxW.jpg",
    description:
      "A secretary embezzles money, goes on the run and checks into a remote motel run by a young man under the domination of his mother.",
  },
  {
    id: 77,
    title: "Vertigo",
    director: "Alfred Hitchcock",
    authors: ["Pierre Boileau", "Thomas Narcejac"],
    year: 1958,
    genre: ["Mystery", "Romance", "Thriller"],
    rating: 8.3,
    duration: 128,
    language: "English",
    image: "https://image.tmdb.org/t/p/w500/5bl4cInSBqmCvzH5Xkd2pXpkUxb.jpg",
    description:
      "A former police detective juggles wrestling with personal demons and becoming obsessed with a hauntingly beautiful woman.",
  },
  {
    id: 78,
    title: "The Intouchables",
    director: "Olivier Nakache",
    authors: ["Olivier Nakache", "Éric Toledano"],
    year: 2011,
    genre: ["Biography", "Comedy", "Drama"],
    rating: 8.5,
    duration: 112,
    language: "French",
    image: "https://image.tmdb.org/t/p/w500/1e866MXyS8HmZOBWRMrCBQVE0bm.jpg",
    description:
      "After becoming a quadriplegic from a paragliding accident, an aristocrat hires a young man from the projects to be his caregiver.",
  },
  {
    id: 79,
    title: "Snow White and the Seven Dwarfs",
    director: "David Hand",
    authors: ["Jacob Grimm", "Wilhelm Grimm"],
    year: 1937,
    genre: ["Animation", "Family", "Fantasy"],
    rating: 7.6,
    duration: 83,
    language: "English",
    image: "https://image.tmdb.org/t/p/w500/qvktm0BHcnmDpul4Hz01GIazWPr.jpg",
    description:
      "Snow White, a kind young princess, escapes the wrath of her jealous stepmother after befriending seven dwarfs.",
  },
  {
    id: 80,
    title: "Dr. Strangelove",
    director: "Stanley Kubrick",
    authors: ["Peter George", "Stanley Kubrick"],
    year: 1964,
    genre: ["Comedy", "War"],
    rating: 8.4,
    duration: 95,
    language: "English",
    image: "https://image.tmdb.org/t/p/w500/gx9FSMfXijcUFSfILmPMHKFdlxS.jpg",
    description:
      "An insane general triggers a path to nuclear holocaust that a War Room full of politicians frantically tries to stop.",
  },
  {
    id: 81,
    title: "Kill Bill: Volume 1",
    director: "Quentin Tarantino",
    authors: ["Quentin Tarantino"],
    year: 2003,
    genre: ["Action", "Crime", "Thriller"],
    rating: 8.2,
    duration: 111,
    language: "English",
    image: "https://image.tmdb.org/t/p/w500/v7TaX8kXMXs5yFFGR41guUDNcnB.jpg",
    description:
      "After awakening from a four-year coma, a former assassin wreaks vengeance on the team of assassins who betrayed her.",
  },
  {
    id: 82,
    title: "Blade Runner",
    director: "Ridley Scott",
    authors: ["Philip K. Dick", "Hampton Fancher"],
    year: 1982,
    genre: ["Action", "Sci-Fi", "Thriller"],
    rating: 8.1,
    duration: 117,
    language: "English",
    image: "https://image.tmdb.org/t/p/w500/63N9uy8nd9j7Eog2axPQ8lbr3Wj.jpg",
    description:
      "A blade runner must pursue and terminate four replicants who returned to Earth to find their creator.",
  },
  {
    id: 83,
    title: "The Big Short",
    director: "Adam McKay",
    authors: ["Michael Lewis", "Charles Randolph"],
    year: 2015,
    genre: ["Biography", "Comedy", "Drama"],
    rating: 7.8,
    duration: 130,
    language: "English",
    image: "https://image.tmdb.org/t/p/w500/dXgmCHDmHFfGhuAZm3pNVNqFjpd.jpg",
    description:
      "In 2006-2007 a group of investors bet against the US mortgage market and discover how flawed and corrupt the market is.",
  },
  {
    id: 84,
    title: "The Hateful Eight",
    director: "Quentin Tarantino",
    authors: ["Quentin Tarantino"],
    year: 2015,
    genre: ["Crime", "Drama", "Mystery"],
    rating: 7.8,
    duration: 167,
    language: "English",
    image: "https://image.tmdb.org/t/p/w500/xDu7v6zaBf4OxbO1JBrZdv9fBwG.jpg",
    description:
      "In the dead of a Wyoming winter, a bounty hunter and his prisoner find shelter in a stagecoach stopover with several other shady characters.",
  },
  {
    id: 85,
    title: "Moonlight",
    director: "Barry Jenkins",
    authors: ["Tarell Alvin McCraney", "Barry Jenkins"],
    year: 2016,
    genre: ["Drama"],
    rating: 7.4,
    duration: 111,
    language: "English",
    image: "https://image.tmdb.org/t/p/w500/4911T5FbJ9eAlnDPQBKBL9wHOgC.jpg",
    description:
      "A young African-American man grapples with his identity and sexuality while experiencing the struggles of childhood through adulthood.",
  },
  {
    id: 86,
    title: "Lawrence of Arabia",
    director: "David Lean",
    authors: ["T.E. Lawrence", "Robert Bolt"],
    year: 1962,
    genre: ["Adventure", "Biography", "Drama"],
    rating: 8.3,
    duration: 216,
    language: "English",
    image: "https://image.tmdb.org/t/p/w500/AiAm0EtRgSGEBnts2c2WxnnfWKa.jpg",
    description:
      "The story of T.E. Lawrence, the English officer who successfully united and led the diverse Arab tribes during World War I.",
  },
  {
    id: 87,
    title: "Boyhood",
    director: "Richard Linklater",
    authors: ["Richard Linklater"],
    year: 2014,
    genre: ["Drama"],
    rating: 7.9,
    duration: 165,
    language: "English",
    image: "https://image.tmdb.org/t/p/w500/sO7xEGwBPyM3VJbFy0x9Dxhq9H2.jpg",
    description:
      "The life of Mason, from early childhood to his arrival at college, filmed over twelve years.",
  },
  {
    id: 88,
    title: "Her",
    director: "Spike Jonze",
    authors: ["Spike Jonze"],
    year: 2013,
    genre: ["Drama", "Romance", "Sci-Fi"],
    rating: 8.0,
    duration: 126,
    language: "English",
    image: "https://image.tmdb.org/t/p/w500/eCOtqtfvn7mxGaRMwbBfXjSUCOt.jpg",
    description:
      "In a near future, a lonely writer develops an unlikely relationship with an operating system designed to meet his every need.",
  },
  {
    id: 89,
    title: "Raiders of the Lost Ark",
    director: "Steven Spielberg",
    authors: ["Lawrence Kasdan", "George Lucas"],
    year: 1981,
    genre: ["Action", "Adventure"],
    rating: 8.4,
    duration: 115,
    language: "English",
    image: "https://image.tmdb.org/t/p/w500/ceG9VzoRAVGwivFU403Wc3AHRys.jpg",
    description:
      "Archaeologist and adventurer Indiana Jones is hired by the U.S. government to find the Ark of the Covenant before the Nazis.",
  },
  {
    id: 90,
    title: "Fargo",
    director: "Joel Coen",
    authors: ["Ethan Coen", "Joel Coen"],
    year: 1996,
    genre: ["Crime", "Drama", "Thriller"],
    rating: 8.1,
    duration: 98,
    language: "English",
    image: "https://image.tmdb.org/t/p/w500/lgCnFtSdXLjZ2hmI8ckJ1F65qgc.jpg",
    description:
      "Jerry Lundegaard's inept crime falls apart due to bungling and the persistent police work of pregnant Marge Gunderson.",
  },
  {
    id: 91,
    title: "E.T. the Extra-Terrestrial",
    director: "Steven Spielberg",
    authors: ["Melissa Mathison"],
    year: 1982,
    genre: ["Family", "Sci-Fi"],
    rating: 7.9,
    duration: 115,
    language: "English",
    image: "https://image.tmdb.org/t/p/w500/an0nD6uq6byfxXCfk7hALKNoHSq.jpg",
    description:
      "A troubled child summons the courage to help a friendly alien escape Earth and return to his home world.",
  },
  {
    id: 92,
    title: "The Sixth Sense",
    director: "M. Night Shyamalan",
    authors: ["M. Night Shyamalan"],
    year: 1999,
    genre: ["Drama", "Mystery", "Thriller"],
    rating: 8.2,
    duration: 107,
    language: "English",
    image: "https://image.tmdb.org/t/p/w500/oUoDwihEBbpnfZdNKXHGBnAlrPT.jpg",
    description:
      "A frightened, withdrawn Philadelphia boy who communicates with spirits seeks the help of a disheartened child psychologist.",
  },
  {
    id: 93,
    title: "Three Billboards Outside Ebbing, Missouri",
    director: "Martin McDonagh",
    authors: ["Martin McDonagh"],
    year: 2017,
    genre: ["Crime", "Drama"],
    rating: 8.1,
    duration: 115,
    language: "English",
    image: "https://image.tmdb.org/t/p/w500/mbX8kraOZhm7i3WJLHNFHCidBXD.jpg",
    description:
      "A mother personally challenges the local authorities to solve her daughter's murder when they fail to catch the culprit.",
  },
  {
    id: 94,
    title: "The Irishman",
    director: "Martin Scorsese",
    authors: ["Charles Brandt", "Steven Zaillian"],
    year: 2019,
    genre: ["Biography", "Crime", "Drama"],
    rating: 7.8,
    duration: 209,
    language: "English",
    image: "https://image.tmdb.org/t/p/w500/mbm8k3GFhXS0ROd9AD1gqYbIFbM.jpg",
    description:
      "An aging hitman recalls his time with the mob and his relationship with Jimmy Hoffa through the 1950s–1980s.",
  },
  {
    id: 95,
    title: "Roma",
    director: "Alfonso Cuarón",
    authors: ["Alfonso Cuarón"],
    year: 2018,
    genre: ["Drama"],
    rating: 7.7,
    duration: 135,
    language: "Spanish",
    image: "https://image.tmdb.org/t/p/w500/dtGtaKnWCJdLOsI59XNMdZbbQLk.jpg",
    description:
      "A year in the life of a middle-class family's maid in Mexico City in the early 1970s.",
  },
  {
    id: 96,
    title: "Atonement",
    director: "Joe Wright",
    authors: ["Ian McEwan", "Christopher Hampton"],
    year: 2007,
    genre: ["Drama", "Mystery", "Romance"],
    rating: 7.8,
    duration: 123,
    language: "English",
    image: "https://image.tmdb.org/t/p/w500/nEyqYCBp65rU5e0WxQGHhEzMzxQ.jpg",
    description:
      "Thirteen-year-old Briony irrevocably changes the course of several lives when she falsely accuses her older sister's lover of a crime.",
  },
  {
    id: 97,
    title: "Catch Me If You Can",
    director: "Steven Spielberg",
    authors: ["Frank Abagnale Jr.", "Jeff Nathanson"],
    year: 2002,
    genre: ["Biography", "Crime", "Drama"],
    rating: 8.1,
    duration: 141,
    language: "English",
    image: "https://image.tmdb.org/t/p/w500/sdRwqTCFWPLEuB02Uj73YvUWKRW.jpg",
    description:
      "Frank W. Abagnale Jr. successfully forged Treasury checks while passing himself off as a Pan Am pilot, a doctor, and a legal prosecutor.",
  },
  {
    id: 98,
    title: "Tenet",
    director: "Christopher Nolan",
    authors: ["Christopher Nolan"],
    year: 2020,
    genre: ["Action", "Sci-Fi", "Thriller"],
    rating: 7.3,
    duration: 150,
    language: "English",
    image: "https://image.tmdb.org/t/p/w500/k68nPLbIST6NP96JmTxmZijZchr.jpg",
    description:
      "Armed with only one word, a Protagonist journeys through a twilight world of international espionage on a mission beyond real time.",
  },
  {
    id: 99,
    title: "Gone with the Wind",
    director: "Victor Fleming",
    authors: ["Margaret Mitchell", "Sidney Howard"],
    year: 1939,
    genre: ["Drama", "History", "Romance"],
    rating: 8.2,
    duration: 238,
    language: "English",
    image: "https://image.tmdb.org/t/p/w500/ym1dxyOk4jFcSl4Q2zmRrA5BEEN.jpg",
    description:
      "A manipulative woman and a roguish man conduct a turbulent romance during the American Civil War and Reconstruction periods.",
  },
  {
    id: 100,
    title: "Prisoners",
    director: "Denis Villeneuve",
    authors: ["Aaron Guzikowski"],
    year: 2013,
    genre: ["Crime", "Drama", "Mystery"],
    rating: 8.1,
    duration: 153,
    language: "English",
    image: "https://image.tmdb.org/t/p/w500/iLBuMZPOhkIGCTmHOgJaRHnN4zt.jpg",
    description:
      "When his daughter and her friend go missing, a father takes matters into his own hands while the police pursue multiple leads.",
  },
  {
    id: 101,
    title: "Zodiac",
    director: "David Fincher",
    authors: ["Robert Graysmith", "James Vanderbilt"],
    year: 2007,
    genre: ["Crime", "Drama", "Mystery"],
    rating: 7.7,
    duration: 157,
    language: "English",
    image: "https://image.tmdb.org/t/p/w500/ogl3MFBuBXFOiEV1RhQjGX7jXHv.jpg",
    description:
      "A San Francisco cartoonist becomes an amateur detective obsessed with the Zodiac Killer in the late 1960s.",
  },
  {
    id: 102,
    title: "Spotlight",
    director: "Tom McCarthy",
    authors: ["Tom McCarthy", "Josh Singer"],
    year: 2015,
    genre: ["Biography", "Crime", "Drama"],
    rating: 8.1,
    duration: 128,
    language: "English",
    image: "https://image.tmdb.org/t/p/w500/e8ooPME2DXQT9Mq8HGi7FmWEVe1.jpg",
    description:
      "The true story of how the Boston Globe uncovered the massive scandal of child molestation within the local Catholic Archdiocese.",
  },
  {
    id: 103,
    title: "12 Years a Slave",
    director: "Steve McQueen",
    authors: ["Solomon Northup", "John Ridley"],
    year: 2013,
    genre: ["Biography", "Drama", "History"],
    rating: 8.1,
    duration: 134,
    language: "English",
    image: "https://image.tmdb.org/t/p/w500/xdHgd8vNVBLSIkEzuGVEeOROcGy.jpg",
    description:
      "Free black man Solomon Northup is abducted and sold into slavery in the antebellum United States.",
  },
  {
    id: 104,
    title: "The Witch",
    director: "Robert Eggers",
    authors: ["Robert Eggers"],
    year: 2015,
    genre: ["Drama", "Fantasy", "Horror"],
    rating: 6.9,
    duration: 92,
    language: "English",
    image: "https://image.tmdb.org/t/p/w500/xsKXWUhm7EBkTdOD9kqBnqnFHoS.jpg",
    description:
      "A family in 1630s New England is torn apart by the forces of witchcraft, black magic, and possession.",
  },
  {
    id: 105,
    title: "Midsommar",
    director: "Ari Aster",
    authors: ["Ari Aster"],
    year: 2019,
    genre: ["Drama", "Horror", "Mystery"],
    rating: 7.1,
    duration: 148,
    language: "English",
    image: "https://image.tmdb.org/t/p/w500/7LEI8ulZzO5gy9Ww2NVCrKmHeDZ.jpg",
    description:
      "A couple travels to Sweden for a midsummer festival that devolves into an increasingly violent and bizarre competition.",
  },
  {
    id: 106,
    title: "Hereditary",
    director: "Ari Aster",
    authors: ["Ari Aster"],
    year: 2018,
    genre: ["Drama", "Horror", "Mystery"],
    rating: 7.3,
    duration: 127,
    language: "English",
    image: "https://image.tmdb.org/t/p/w500/p9YAsmZnOkbqxS27QeWXiw3WMOX.jpg",
    description:
      "A grieving family is haunted by tragic and disturbing occurrences after the death of their secretive grandmother.",
  },
  {
    id: 107,
    title: "A Quiet Place",
    director: "John Krasinski",
    authors: ["Bryan Woods", "Scott Beck"],
    year: 2018,
    genre: ["Drama", "Horror", "Sci-Fi"],
    rating: 7.5,
    duration: 90,
    language: "English",
    image: "https://image.tmdb.org/t/p/w500/nAU74GmpUk7t5iklEp3bufwDq4n.jpg",
    description:
      "In a post-apocalyptic world, a family is forced to live in silence while hiding from monsters with ultra-sensitive hearing.",
  },
  {
    id: 108,
    title: "Arrival",
    director: "Denis Villeneuve",
    authors: ["Ted Chiang", "Eric Heisserer"],
    year: 2016,
    genre: ["Drama", "Mystery", "Sci-Fi"],
    rating: 7.9,
    duration: 116,
    language: "English",
    image: "https://image.tmdb.org/t/p/w500/x2FJsf1ElAgr63Y3PNPtJrcmpoe.jpg",
    description:
      "A linguist works with the military to communicate with alien lifeforms after twelve mysterious spacecraft appear around the world.",
  },
  {
    id: 109,
    title: "Dune",
    director: "Denis Villeneuve",
    authors: ["Frank Herbert", "Jon Spaihts"],
    year: 2021,
    genre: ["Action", "Adventure", "Drama"],
    rating: 8.0,
    duration: 155,
    language: "English",
    image: "https://image.tmdb.org/t/p/w500/d5NXSklpcvweasQVX9IOkay5HCa.jpg",
    description:
      "A noble family becomes embroiled in a war for control over the galaxy's most valuable asset while its heir is troubled by visions of a dark future.",
  },
  {
    id: 110,
    title: "Shutter Island",
    director: "Martin Scorsese",
    authors: ["Dennis Lehane", "Laeta Kalogridis"],
    year: 2010,
    genre: ["Mystery", "Thriller"],
    rating: 8.2,
    duration: 138,
    language: "English",
    image: "https://image.tmdb.org/t/p/w500/pXm4y9iOGmLBjqmUbXDuGJLVNup.jpg",
    description:
      "In 1954, a U.S. Marshal investigates the disappearance of a murderer who escaped from a hospital for the criminally insane.",
  },
  {
    id: 111,
    title: "The Lighthouse",
    director: "Robert Eggers",
    authors: ["Robert Eggers", "Max Eggers"],
    year: 2019,
    genre: ["Drama", "Fantasy", "Horror"],
    rating: 7.4,
    duration: 109,
    language: "English",
    image: "https://image.tmdb.org/t/p/w500/3nk9UoepYmv1G9oP18q6JJtnsly.jpg",
    description:
      "Two lighthouse keepers try to maintain their sanity while living on a remote and mysterious New England island in the 1890s.",
  },
  {
    id: 112,
    title: "Akira",
    director: "Katsuhiro Otomo",
    authors: ["Katsuhiro Otomo"],
    year: 1988,
    genre: ["Animation", "Action", "Sci-Fi"],
    rating: 8.0,
    duration: 124,
    language: "Japanese",
    image: "https://image.tmdb.org/t/p/w500/tTp5d84wgvBjBpVw5eEPIpKdaL6.jpg",
    description:
      "A secret military project endangers Neo-Tokyo when it turns a biker gang member into a rampaging psychic.",
  },
  {
    id: 113,
    title: "Grave of the Fireflies",
    director: "Isao Takahata",
    authors: ["Akiyuki Nosaka", "Isao Takahata"],
    year: 1988,
    genre: ["Animation", "Drama", "War"],
    rating: 8.5,
    duration: 89,
    language: "Japanese",
    image: "https://image.tmdb.org/t/p/w500/2dyBeaLBFN6Iqhbn8u3A9Qm1dDZ.jpg",
    description:
      "A young boy and his little sister struggle to survive in Japan during World War II.",
  },
  {
    id: 114,
    title: "Seven Samurai",
    director: "Akira Kurosawa",
    authors: ["Akira Kurosawa", "Shinobu Hashimoto"],
    year: 1954,
    genre: ["Action", "Adventure", "Drama"],
    rating: 8.6,
    duration: 207,
    language: "Japanese",
    image: "https://image.tmdb.org/t/p/w500/8OKmBV5BUFzmozIC3pPWKHy17kx.jpg",
    description:
      "A poor village under attack by bandits recruits seven unemployed samurai to help them defend themselves.",
  },
  {
    id: 115,
    title: "In the Mood for Love",
    director: "Wong Kar-wai",
    authors: ["Wong Kar-wai"],
    year: 2000,
    genre: ["Drama", "Romance"],
    rating: 8.1,
    duration: 99,
    language: "Cantonese",
    image: "https://image.tmdb.org/t/p/w500/4MRm8t5OJXO3SKm5MLdrGhBhHWX.jpg",
    description:
      "Two neighbors form a strong bond after both suspect extramarital activities of their spouses, agreeing to keep their bond platonic.",
  },
  {
    id: 116,
    title: "Come and See",
    director: "Elem Klimov",
    authors: ["Ales Adamovich", "Elem Klimov"],
    year: 1985,
    genre: ["Drama", "War"],
    rating: 8.4,
    duration: 142,
    language: "Russian",
    image: "https://image.tmdb.org/t/p/w500/2YsTHCPQFyGNYNQD0j8t8kQDdrL.jpg",
    description:
      "A Soviet boy joins the resistance movement against ruthless German forces and experiences the horrors of World War II.",
  },
  {
    id: 117,
    title: "Bicycle Thieves",
    director: "Vittorio De Sica",
    authors: ["Luigi Bartolini", "Cesare Zavattini"],
    year: 1948,
    genre: ["Drama"],
    rating: 8.3,
    duration: 89,
    language: "Italian",
    image: "https://image.tmdb.org/t/p/w500/7oRi4qdRmZi1bdh9wkRAtpygvxK.jpg",
    description:
      "In postwar Italy, a poor man's bicycle is stolen, threatening his new job. He and his son search Rome for it.",
  },
  {
    id: 118,
    title: "Cinema Paradiso",
    director: "Giuseppe Tornatore",
    authors: ["Giuseppe Tornatore"],
    year: 1988,
    genre: ["Drama", "Romance"],
    rating: 8.5,
    duration: 155,
    language: "Italian",
    image: "https://image.tmdb.org/t/p/w500/8SRUfRUi6x4O68n0VCbDNRa6iGL.jpg",
    description:
      "A filmmaker recalls his childhood falling in love with the pictures at his village cinema and his deep friendship with the projectionist.",
  },
  {
    id: 119,
    title: "Wild Strawberries",
    director: "Ingmar Bergman",
    authors: ["Ingmar Bergman"],
    year: 1957,
    genre: ["Drama"],
    rating: 8.2,
    duration: 91,
    language: "Swedish",
    image: "https://image.tmdb.org/t/p/w500/pVSQF8TvmfstR1sGIxb3zM5kVJL.jpg",
    description:
      "After living a cold and apathetic life, an aging professor is finally forced to confront the emptiness of his existence.",
  },
  {
    id: 120,
    title: "M",
    director: "Fritz Lang",
    authors: ["Thea von Harbou", "Fritz Lang"],
    year: 1931,
    genre: ["Crime", "Mystery", "Thriller"],
    rating: 8.3,
    duration: 99,
    language: "German",
    image: "https://image.tmdb.org/t/p/w500/FPaqRufNxTa9EDfgLKMv2EqN1rt.jpg",
    description:
      "When police in a German city are unable to catch a child-murderer, other criminals decide to find the perpetrator themselves.",
  },
  {
    id: 121,
    title: "Metropolis",
    director: "Fritz Lang",
    authors: ["Fritz Lang", "Thea von Harbou"],
    year: 1927,
    genre: ["Drama", "Sci-Fi"],
    rating: 8.3,
    duration: 153,
    language: "German",
    image: "https://image.tmdb.org/t/p/w500/fP6s8ODdA4o5wrSSf8sIsqhXI1w.jpg",
    description:
      "In a futuristic city divided between workers and planners, the mastermind's son falls in love with a working-class prophet.",
  },
  {
    id: 122,
    title: "Rashomon",
    director: "Akira Kurosawa",
    authors: ["Ryunosuke Akutagawa", "Akira Kurosawa"],
    year: 1950,
    genre: ["Crime", "Drama", "Mystery"],
    rating: 8.2,
    duration: 88,
    language: "Japanese",
    image: "https://image.tmdb.org/t/p/w500/w9wuRuZnbDJBEtmVpBrXzjblXe8.jpg",
    description:
      "The rape of a samurai's wife and murder of her husband are recalled from the conflicting perspectives of four witnesses.",
  },
  {
    id: 123,
    title: "Breathless",
    director: "Jean-Luc Godard",
    authors: ["François Truffaut", "Jean-Luc Godard"],
    year: 1960,
    genre: ["Crime", "Drama"],
    rating: 7.8,
    duration: 90,
    language: "French",
    image: "https://image.tmdb.org/t/p/w500/lW58SGz6O3NPlIHGktXfr1k6lzR.jpg",
    description:
      "A small-time thief murders a policeman and reunites with an American journalism student, attempting to persuade her to flee to Italy.",
  },
  {
    id: 124,
    title: "Tokyo Story",
    director: "Yasujiro Ozu",
    authors: ["Kogo Noda", "Yasujiro Ozu"],
    year: 1953,
    genre: ["Drama"],
    rating: 8.2,
    duration: 136,
    language: "Japanese",
    image: "https://image.tmdb.org/t/p/w500/rMhBtOj5GKDQ3nfFUHKLFe5FbdS.jpg",
    description:
      "An old couple visits their children and grandchildren in the city, only to find the children have little time for them.",
  },
  {
    id: 125,
    title: "Persona",
    director: "Ingmar Bergman",
    authors: ["Ingmar Bergman"],
    year: 1966,
    genre: ["Drama", "Mystery"],
    rating: 8.1,
    duration: 83,
    language: "Swedish",
    image: "https://image.tmdb.org/t/p/w500/7qFMKA6kfuBVKKLYLWqEj3ldkdO.jpg",
    description:
      "A nurse is put in charge of a mute actress and finds that the actress's persona is melding with her own.",
  },
  {
    id: 126,
    title: "8½",
    director: "Federico Fellini",
    authors: ["Federico Fellini", "Tullio Pinelli"],
    year: 1963,
    genre: ["Drama"],
    rating: 8.0,
    duration: 138,
    language: "Italian",
    image: "https://image.tmdb.org/t/p/w500/w4wHNhHcJFhEF8DdVFbcxNDsw5G.jpg",
    description:
      "A film director on the verge of a breakdown retreats into memories, fantasies and dreams while trying to complete an ambitious film.",
  },
  {
    id: 127,
    title: "The 400 Blows",
    director: "François Truffaut",
    authors: ["François Truffaut", "Marcel Moussy"],
    year: 1959,
    genre: ["Crime", "Drama"],
    rating: 8.1,
    duration: 99,
    language: "French",
    image: "https://image.tmdb.org/t/p/w500/eEHze62YPFVR2s7P0mUEEelPNf4.jpg",
    description:
      "A 12-year-old boy left without attention by his troubled parents turns to petty crime and quickly spirals out of control.",
  },
  {
    id: 128,
    title: "Stalker",
    director: "Andrei Tarkovsky",
    authors: ["Arkady Strugatsky", "Boris Strugatsky"],
    year: 1979,
    genre: ["Drama", "Sci-Fi"],
    rating: 8.2,
    duration: 162,
    language: "Russian",
    image: "https://image.tmdb.org/t/p/w500/jmvVVZJBPV5YODvh94L8sTGVwv5.jpg",
    description:
      "A guide leads two men through an area known as the Zone to find a room that grants wishes.",
  },
  {
    id: 129,
    title: "Andrei Rublev",
    director: "Andrei Tarkovsky",
    authors: ["Andrei Tarkovsky", "Andrei Konchalovsky"],
    year: 1966,
    genre: ["Biography", "Drama", "History"],
    rating: 8.1,
    duration: 183,
    language: "Russian",
    image: "https://image.tmdb.org/t/p/w500/a1jHCKLJIzCsAVjEPFRnXi8IUEn.jpg",
    description:
      "The life, times and afflictions of the fifteenth-century Russian icon painter Andrei Rublev.",
  },
  {
    id: 130,
    title: "Mirror",
    director: "Andrei Tarkovsky",
    authors: ["Aleksandr Misharin", "Andrei Tarkovsky"],
    year: 1975,
    genre: ["Biography", "Drama", "Fantasy"],
    rating: 8.2,
    duration: 108,
    language: "Russian",
    image: "https://image.tmdb.org/t/p/w500/ufG3ePJrMFEXC1VBmpGFQyX7qqC.jpg",
    description:
      "A dying man in his forties remembers his past, interwoven with shots of his mother and ex-wife.",
  },
  {
    id: 131,
    title: "Network",
    director: "Sidney Lumet",
    authors: ["Paddy Chayefsky"],
    year: 1976,
    genre: ["Drama"],
    rating: 8.1,
    duration: 121,
    language: "English",
    image: "https://image.tmdb.org/t/p/w500/gLlnpGUBP9gYxKS6SdCTTbz04X5.jpg",
    description:
      "A television network cynically exploits a deranged former anchor's ravings about the corporate ownership of the news media.",
  },
  {
    id: 132,
    title: "Sunset Boulevard",
    director: "Billy Wilder",
    authors: ["Charles Brackett", "Billy Wilder"],
    year: 1950,
    genre: ["Drama", "Film-Noir"],
    rating: 8.5,
    duration: 110,
    language: "English",
    image: "https://image.tmdb.org/t/p/w500/qyRBa7PTJ7N9K1hVuCw5VjwHVPh.jpg",
    description:
      "A screenwriter develops a dangerous relationship with a faded film star determined to make a triumphant return.",
  },
  {
    id: 133,
    title: "Double Indemnity",
    director: "Billy Wilder",
    authors: ["James M. Cain", "Billy Wilder"],
    year: 1944,
    genre: ["Crime", "Drama", "Film-Noir"],
    rating: 8.3,
    duration: 107,
    language: "English",
    image: "https://image.tmdb.org/t/p/w500/dTBpC0X6CRbXgMd1IkgOjmMPpK5.jpg",
    description:
      "An insurance representative lets himself be talked into a murder/insurance fraud scheme that arouses an investigator's suspicions.",
  },
  {
    id: 134,
    title: "Some Like It Hot",
    director: "Billy Wilder",
    authors: ["Robert Thoeren", "Billy Wilder"],
    year: 1959,
    genre: ["Comedy", "Crime", "Romance"],
    rating: 8.2,
    duration: 121,
    language: "English",
    image: "https://image.tmdb.org/t/p/w500/nif7pFEXDS5GsJlIEPpRLVAuAmm.jpg",
    description:
      "Two musicians witness a mob hit and disguise themselves as members of an all-female band to avoid the gangsters.",
  },
  {
    id: 135,
    title: "Rear Window",
    director: "Alfred Hitchcock",
    authors: ["Cornell Woolrich", "John Michael Hayes"],
    year: 1954,
    genre: ["Mystery", "Thriller"],
    rating: 8.5,
    duration: 112,
    language: "English",
    image: "https://image.tmdb.org/t/p/w500/ILVF0eJxHMddjxeQhswFtpMtqx.jpg",
    description:
      "A photographer with a broken leg spies on his neighbors through his rear window and believes he witnesses a murder.",
  },
  {
    id: 136,
    title: "North by Northwest",
    director: "Alfred Hitchcock",
    authors: ["Ernest Lehman"],
    year: 1959,
    genre: ["Action", "Adventure", "Mystery"],
    rating: 8.3,
    duration: 136,
    language: "English",
    image: "https://image.tmdb.org/t/p/w500/ddABdjfQ11hKFJgPJURxjOEKEjQ.jpg",
    description:
      "A New York City advertising executive goes on the run after being mistaken for a government agent by foreign spies.",
  },
  {
    id: 137,
    title: "All About Eve",
    director: "Joseph L. Mankiewicz",
    authors: ["Mary Orr", "Joseph L. Mankiewicz"],
    year: 1950,
    genre: ["Drama"],
    rating: 8.2,
    duration: 138,
    language: "English",
    image: "https://image.tmdb.org/t/p/w500/2WnEsKMUJxfDoBQNvTFbSJQjlP1.jpg",
    description:
      "An ingenue insinuates herself into the company of an established but aging stage actress and her circle of theater friends.",
  },
  {
    id: 138,
    title: "Citizen Kane",
    director: "Orson Welles",
    authors: ["Herman J. Mankiewicz", "Orson Welles"],
    year: 1941,
    genre: ["Drama", "Mystery"],
    rating: 8.3,
    duration: 119,
    language: "English",
    image: "https://image.tmdb.org/t/p/w500/sav0jxhqiH0bPr2vZFU0Kjt2nZL.jpg",
    description:
      "Following the death of publishing tycoon Charles Foster Kane, reporters scramble to uncover the meaning of his final utterance.",
  },
  {
    id: 139,
    title: "Singin' in the Rain",
    director: "Stanley Donen",
    authors: ["Betty Comden", "Adolph Green"],
    year: 1952,
    genre: ["Comedy", "Musical", "Romance"],
    rating: 8.3,
    duration: 103,
    language: "English",
    image: "https://image.tmdb.org/t/p/w500/w1AZNXkWJn6gBIFqSWNmMkNBNxE.jpg",
    description:
      "A silent film production company and cast make a difficult transition to sound.",
  },
  {
    id: 140,
    title: "Chinatown",
    director: "Roman Polanski",
    authors: ["Robert Towne"],
    year: 1974,
    genre: ["Drama", "Mystery", "Thriller"],
    rating: 8.2,
    duration: 130,
    language: "English",
    image: "https://image.tmdb.org/t/p/w500/kNLP6g0zD0UVoFyAaGcgGzj0ydH.jpg",
    description:
      "A private detective hired to expose an adulterer in 1930s Los Angeles finds himself caught in a web of deceit, corruption, and murder.",
  },
  {
    id: 141,
    title: "The Deer Hunter",
    director: "Michael Cimino",
    authors: ["Deric Washburn"],
    year: 1978,
    genre: ["Drama", "War"],
    rating: 8.2,
    duration: 183,
    language: "English",
    image: "https://image.tmdb.org/t/p/w500/yNMZVrCrq4GJgOUVaKSbCsaGxpL.jpg",
    description:
      "An in-depth examination of how the Vietnam War affects the lives of people in a small industrial Pennsylvania town.",
  },
  {
    id: 142,
    title: "Once Upon a Time in America",
    director: "Sergio Leone",
    authors: ["Harry Grey", "Leonardo Benvenuti"],
    year: 1984,
    genre: ["Crime", "Drama"],
    rating: 8.4,
    duration: 229,
    language: "English",
    image: "https://image.tmdb.org/t/p/w500/q4LNgUnRfltxzp3gf1MAGiK5LhV.jpg",
    description:
      "A former Prohibition-era Jewish gangster returns to the Lower East Side of Manhattan 35 years later to confront the ghosts of his old life.",
  },
  {
    id: 143,
    title: "Ran",
    director: "Akira Kurosawa",
    authors: ["Akira Kurosawa", "Hideo Oguni"],
    year: 1985,
    genre: ["Action", "Drama", "War"],
    rating: 8.2,
    duration: 162,
    language: "Japanese",
    image: "https://image.tmdb.org/t/p/w500/jz8FPc0SZfkM0bxJFzWpDdQ9DMb.jpg",
    description:
      "In Medieval Japan, an aging warlord retires to yield power to his three sons, causing a political power struggle.",
  },
  {
    id: 144,
    title: "Aguirre, the Wrath of God",
    director: "Werner Herzog",
    authors: ["Werner Herzog"],
    year: 1972,
    genre: ["Adventure", "Drama", "History"],
    rating: 7.9,
    duration: 95,
    language: "German",
    image: "https://image.tmdb.org/t/p/w500/yKDlflqfj35tBkjx0pqLU0sKBVF.jpg",
    description:
      "Spanish conquistador Don Lope de Aguirre leads a doomed expedition down the Amazon in search of El Dorado.",
  },
  {
    id: 145,
    title: "The Battle of Algiers",
    director: "Gillo Pontecorvo",
    authors: ["Franco Solinas", "Gillo Pontecorvo"],
    year: 1966,
    genre: ["Drama", "History", "Thriller"],
    rating: 8.1,
    duration: 121,
    language: "Arabic",
    image: "https://image.tmdb.org/t/p/w500/cHMGR6Yh4VGGmb5OX8IgioVqHtC.jpg",
    description:
      "Fear and violence escalate as Algerian nationalist insurgents attack the French colonial authorities during the Algerian War.",
  },
  {
    id: 146,
    title: "The Conversation",
    director: "Francis Ford Coppola",
    authors: ["Francis Ford Coppola"],
    year: 1974,
    genre: ["Drama", "Mystery", "Thriller"],
    rating: 7.9,
    duration: 113,
    language: "English",
    image: "https://image.tmdb.org/t/p/w500/8CuuNIKMzMUL1NKOPv9AqEwM7og.jpg",
    description:
      "A paranoid surveillance expert has a crisis of conscience when he suspects a couple he is spying on will be murdered.",
  },
  {
    id: 147,
    title: "Se7en",
    director: "David Fincher",
    authors: ["Andrew Kevin Walker"],
    year: 1995,
    genre: ["Crime", "Drama", "Mystery"],
    rating: 8.6,
    duration: 127,
    language: "English",
    image: "https://image.tmdb.org/t/p/w500/6yoghtyTpznpBik8EngEmJskVUO.jpg",
    description:
      "Two detectives, a rookie and a veteran, hunt a serial killer who uses the seven deadly sins as his motives.",
  },
  {
    id: 148,
    title: "The Usual Suspects",
    director: "Bryan Singer",
    authors: ["Christopher McQuarrie"],
    year: 1995,
    genre: ["Crime", "Drama", "Mystery"],
    rating: 8.5,
    duration: 106,
    language: "English",
    image: "https://image.tmdb.org/t/p/w500/bUbWbXlPedaQrlGQS2DfFxhkm7V.jpg",
    description:
      "The sole survivor of a pier shoot-out tells the story of how a notorious crime lord manipulated the events that led to it.",
  },
  {
    id: 149,
    title: "Reservoir Dogs",
    director: "Quentin Tarantino",
    authors: ["Quentin Tarantino"],
    year: 1992,
    genre: ["Crime", "Drama", "Thriller"],
    rating: 8.3,
    duration: 99,
    language: "English",
    image: "https://image.tmdb.org/t/p/w500/lsBn8BkBQ4WqHwhHMBBfRbqdSfR.jpg",
    description:
      "When a simple jewelry heist goes horribly wrong, the surviving criminals begin to suspect that one of them is a police informant.",
  },
  {
    id: 150,
    title: "Taxi Driver",
    director: "Martin Scorsese",
    authors: ["Paul Schrader"],
    year: 1976,
    genre: ["Crime", "Drama"],
    rating: 8.2,
    duration: 114,
    language: "English",
    image: "https://image.tmdb.org/t/p/w500/2LqaLgk4Z226KkgPJuiOQ58ShpS.jpg",
    description:
      "A mentally unstable veteran works as a nighttime taxi driver in New York City, fueled by his urge to violently clean up the city.",
  },
  {
    id: 151,
    title: "Magnolia",
    director: "Paul Thomas Anderson",
    authors: ["Paul Thomas Anderson"],
    year: 1999,
    genre: ["Drama"],
    rating: 8.0,
    duration: 188,
    language: "English",
    image: "https://image.tmdb.org/t/p/w500/nBiB7GTFKsHqtUzBIbAYBFnUMBY.jpg",
    description:
      "An epic mosaic of interrelated characters in search of happiness, forgiveness, and meaning in the San Fernando Valley.",
  },
  {
    id: 152,
    title: "Trainspotting",
    director: "Danny Boyle",
    authors: ["Irvine Welsh", "John Hodge"],
    year: 1996,
    genre: ["Drama"],
    rating: 8.1,
    duration: 94,
    language: "English",
    image: "https://image.tmdb.org/t/p/w500/eAfOzDmHGnqNKUH4KDIe0ldKjSF.jpg",
    description:
      "Renton, deeply immersed in the Edinburgh drug scene, tries to clean up and get out despite the allure of the drugs and influence of friends.",
  },
  {
    id: 153,
    title: "Slumdog Millionaire",
    director: "Danny Boyle",
    authors: ["Vikas Swarup", "Simon Beaufoy"],
    year: 2008,
    genre: ["Crime", "Drama", "Romance"],
    rating: 8.0,
    duration: 120,
    language: "English",
    image: "https://image.tmdb.org/t/p/w500/ALutG9ErNbsNBnlhFNXmxs6Nvdi.jpg",
    description:
      "A teenager from the slums of Mumbai becomes a contestant on the Hindi version of 'Who Wants to Be a Millionaire?' and is suspected of cheating.",
  },
  {
    id: 154,
    title: "Blood Diamond",
    director: "Edward Zwick",
    authors: ["Charles Leavitt"],
    year: 2006,
    genre: ["Adventure", "Drama", "Thriller"],
    rating: 8.0,
    duration: 143,
    language: "English",
    image: "https://image.tmdb.org/t/p/w500/hQzHSJJivDhbhHp4UrqKKP57PVo.jpg",
    description:
      "A diamond smuggler and a fisherman join forces to recover a rare diamond while a country is ravaged by civil war.",
  },
  {
    id: 155,
    title: "Hotel Rwanda",
    director: "Terry George",
    authors: ["Terry George", "Keir Pearson"],
    year: 2004,
    genre: ["Biography", "Drama", "History"],
    rating: 8.1,
    duration: 121,
    language: "English",
    image: "https://image.tmdb.org/t/p/w500/5XPPB44RQGFkBdDNRqnJSon5mFd.jpg",
    description:
      "A hotel manager risks his life to protect over a thousand Tutsi refugees from the violent Hutu militia during the Rwandan genocide.",
  },
  {
    id: 156,
    title: "Children of Men",
    director: "Alfonso Cuarón",
    authors: ["P.D. James", "Alfonso Cuarón"],
    year: 2006,
    genre: ["Action", "Drama", "Sci-Fi"],
    rating: 7.9,
    duration: 109,
    language: "English",
    image: "https://image.tmdb.org/t/p/w500/xMKMEnmcRToSVuTaSsq5s3MPJ8C.jpg",
    description:
      "In 2027 where women have become infertile, a former activist agrees to help transport a miraculously pregnant woman to a sanctuary at sea.",
  },
  {
    id: 157,
    title: "Crouching Tiger, Hidden Dragon",
    director: "Ang Lee",
    authors: ["Wang Du Lu", "James Schamus"],
    year: 2000,
    genre: ["Action", "Adventure", "Drama"],
    rating: 7.9,
    duration: 120,
    language: "Mandarin",
    image: "https://image.tmdb.org/t/p/w500/6f0mRF8xqSMhiVLoqFUjYBkCR7f.jpg",
    description:
      "A young Chinese warrior steals a sword from a famed swordsman and escapes into a world of romantic adventure with a mysterious man.",
  },
  {
    id: 158,
    title: "Spring, Summer, Fall, Winter… and Spring",
    director: "Kim Ki-duk",
    authors: ["Kim Ki-duk"],
    year: 2003,
    genre: ["Drama"],
    rating: 8.0,
    duration: 103,
    language: "Korean",
    image: "https://image.tmdb.org/t/p/w500/d1j9FLi43o9P7B08qFgQCB1xFBs.jpg",
    description:
      "A young Buddhist monk grows up and eventually succeeds his master on a floating monastery.",
  },
  {
    id: 159,
    title: "Portrait of a Lady on Fire",
    director: "Céline Sciamma",
    authors: ["Céline Sciamma"],
    year: 2019,
    genre: ["Drama", "Romance"],
    rating: 8.1,
    duration: 122,
    language: "French",
    image: "https://image.tmdb.org/t/p/w500/3x3GHqkfQEfQHW9kY2bK3qe28lh.jpg",
    description:
      "On an isolated island in 18th-century Brittany, a female painter is obliged to paint a wedding portrait of a young woman.",
  },
  {
    id: 160,
    title: "Burning",
    director: "Lee Chang-dong",
    authors: ["Haruki Murakami", "Oh Jung-mi"],
    year: 2018,
    genre: ["Drama", "Mystery", "Thriller"],
    rating: 7.5,
    duration: 148,
    language: "Korean",
    image: "https://image.tmdb.org/t/p/w500/cBnakQujXRMgq0kHnPRB2F7HQBY.jpg",
    description:
      "Jong-su reconnects with a childhood neighbor who returns from Africa with a mysterious new friend who shares a disturbing hobby.",
  },
  {
    id: 161,
    title: "The Hurt Locker",
    director: "Kathryn Bigelow",
    authors: ["Mark Boal"],
    year: 2008,
    genre: ["Drama", "History", "Thriller"],
    rating: 7.6,
    duration: 131,
    language: "English",
    image: "https://image.tmdb.org/t/p/w500/49MLGbfNhyEMFMHOmSaBuVsOPdT.jpg",
    description:
      "During the Iraq War, a Sergeant recently assigned to an army bomb squad handles dangerous situations in maverick ways.",
  },
  {
    id: 162,
    title: "Zero Dark Thirty",
    director: "Kathryn Bigelow",
    authors: ["Mark Boal"],
    year: 2012,
    genre: ["Drama", "History", "Thriller"],
    rating: 7.4,
    duration: 157,
    language: "English",
    image: "https://image.tmdb.org/t/p/w500/7TbNbFVdSKfWo6C8bN4fHqpQQH2.jpg",
    description:
      "A chronicle of the decade-long hunt for Osama bin Laden after the September 2001 attacks and his death at the hands of Navy SEALs.",
  },
  {
    id: 163,
    title: "Sicario",
    director: "Denis Villeneuve",
    authors: ["Taylor Sheridan"],
    year: 2015,
    genre: ["Action", "Crime", "Drama"],
    rating: 7.6,
    duration: 121,
    language: "English",
    image: "https://image.tmdb.org/t/p/w500/4lCuELQFCGIRGX3YXRxz4NHO9CZ.jpg",
    description:
      "An idealistic FBI agent is enlisted by a government task force to aid in the war against drugs at the U.S.-Mexican border.",
  },
  {
    id: 164,
    title: "Hell or High Water",
    director: "David Mackenzie",
    authors: ["Taylor Sheridan"],
    year: 2016,
    genre: ["Crime", "Drama", "Western"],
    rating: 7.7,
    duration: 102,
    language: "English",
    image: "https://image.tmdb.org/t/p/w500/ygJ6bgFmrCBwKLyQzJuSLCMdNqS.jpg",
    description:
      "A divorced father and his ex-con brother resort to a desperate scheme in order to save their family's ranch in West Texas.",
  },
  {
    id: 165,
    title: "Nightcrawler",
    director: "Dan Gilroy",
    authors: ["Dan Gilroy"],
    year: 2014,
    genre: ["Crime", "Drama", "Thriller"],
    rating: 7.9,
    duration: 117,
    language: "English",
    image: "https://image.tmdb.org/t/p/w500/8DhFzSz2QhMzJYo0GEZsGJVRRKQ.jpg",
    description:
      "When Louis Bloom muscles into the world of L.A. crime journalism, he blurs the line between observer and participant.",
  },
  {
    id: 166,
    title: "Gone Girl",
    director: "David Fincher",
    authors: ["Gillian Flynn"],
    year: 2014,
    genre: ["Drama", "Mystery", "Thriller"],
    rating: 8.1,
    duration: 149,
    language: "English",
    image: "https://image.tmdb.org/t/p/w500/fSRb7vyIP8rQpL0I47P3qUsEKX3.jpg",
    description:
      "With his wife's disappearance becoming a media circus, a man sees the spotlight turned on him as a murder suspect.",
  },
  {
    id: 167,
    title: "The Favourite",
    director: "Yorgos Lanthimos",
    authors: ["Deborah Davis", "Tony McNamara"],
    year: 2018,
    genre: ["Biography", "Comedy", "Drama"],
    rating: 7.5,
    duration: 119,
    language: "English",
    image: "https://image.tmdb.org/t/p/w500/9EI5PAnPwBOsGGGelWFiAkLuqhD.jpg",
    description:
      "In early 18th century England, a frail Queen Anne and her close friend Lady Sarah Churchill are challenged by a scheming new servant.",
  },
  {
    id: 168,
    title: "The Lobster",
    director: "Yorgos Lanthimos",
    authors: ["Yorgos Lanthimos", "Efthymis Filippou"],
    year: 2015,
    genre: ["Comedy", "Drama", "Romance"],
    rating: 7.1,
    duration: 118,
    language: "English",
    image: "https://image.tmdb.org/t/p/w500/7F4YtNq7efS6KMXVF12j1BQYKRK.jpg",
    description:
      "In a dystopian near future, single people are taken to a hotel where they must find a romantic partner or be transformed into animals.",
  },
  {
    id: 169,
    title: "Pain and Glory",
    director: "Pedro Almodóvar",
    authors: ["Pedro Almodóvar"],
    year: 2019,
    genre: ["Drama"],
    rating: 7.5,
    duration: 113,
    language: "Spanish",
    image: "https://image.tmdb.org/t/p/w500/3IRPmPuHHnNcSPQWXlEKBkBFgpT.jpg",
    description:
      "A film director reflects on the choices he's made in life as past and present come crashing down around him.",
  },
  {
    id: 170,
    title: "Once Upon a Time in Hollywood",
    director: "Quentin Tarantino",
    authors: ["Quentin Tarantino"],
    year: 2019,
    genre: ["Comedy", "Drama"],
    rating: 7.6,
    duration: 161,
    language: "English",
    image: "https://image.tmdb.org/t/p/w500/8j58iEBw9pOXFD2L0nt0ZXeHviB.jpg",
    description:
      "A faded television actor and his stunt double strive to achieve fame in the final years of Hollywood's Golden Age in 1969.",
  },
  {
    id: 171,
    title: "The 40-Year-Old Virgin",
    director: "Judd Apatow",
    authors: ["Judd Apatow", "Steve Carell"],
    year: 2005,
    genre: ["Comedy", "Romance"],
    rating: 7.1,
    duration: 116,
    language: "English",
    image: "https://image.tmdb.org/t/p/w500/pBn8bbGDR30CzOAoRHHm0mLfH7M.jpg",
    description:
      "Goaded by his friends, a nerdy, middle-aged virgin decides to get back into the dating scene.",
  },
  {
    id: 172,
    title: "Superbad",
    director: "Greg Mottola",
    authors: ["Seth Rogen", "Evan Goldberg"],
    year: 2007,
    genre: ["Comedy"],
    rating: 7.6,
    duration: 113,
    language: "English",
    image: "https://image.tmdb.org/t/p/w500/ek8e8txUyUwd2BNqj6lFEerJfbq.jpg",
    description:
      "Two co-dependent high school seniors are forced to deal with separation anxiety after their plan to buy alcohol for a party goes awry.",
  },
  {
    id: 173,
    title: "The Hangover",
    director: "Todd Phillips",
    authors: ["Jon Lucas", "Scott Moore"],
    year: 2009,
    genre: ["Comedy"],
    rating: 7.7,
    duration: 100,
    language: "English",
    image: "https://image.tmdb.org/t/p/w500/uluhlXubGu1VxU63boEOz3skBB9.jpg",
    description:
      "Three buddies wake up from a bachelor party in Las Vegas with no memory of the previous night and the groom missing.",
  },
  {
    id: 174,
    title: "Bridesmaids",
    director: "Paul Feig",
    authors: ["Kristen Wiig", "Annie Mumolo"],
    year: 2011,
    genre: ["Comedy", "Romance"],
    rating: 6.8,
    duration: 125,
    language: "English",
    image: "https://image.tmdb.org/t/p/w500/jDtaLlWnKdSfr0Y0oKzLZzH3SnS.jpg",
    description:
      "Competition between the maid of honor and a bridesmaid, over who is the bride's best friend, threatens to upend the wedding.",
  },
  {
    id: 175,
    title: "Get Shorty",
    director: "Barry Sonnenfeld",
    authors: ["Elmore Leonard", "Scott Frank"],
    year: 1995,
    genre: ["Comedy", "Crime", "Drama"],
    rating: 7.0,
    duration: 105,
    language: "English",
    image: "https://image.tmdb.org/t/p/w500/tHFp8WYNAkAlzUWFa2Hs7Fmlq0.jpg",
    description:
      "A Miami loan shark travels to Hollywood, where he gets involved in the movie business.",
  },
  {
    id: 176,
    title: "O Brother, Where Art Thou?",
    director: "Joel Coen",
    authors: ["Ethan Coen", "Joel Coen"],
    year: 2000,
    genre: ["Adventure", "Comedy", "Crime"],
    rating: 7.7,
    duration: 107,
    language: "English",
    image: "https://image.tmdb.org/t/p/w500/etcDWCZAEBdKTRi8LkGqhqyahsA.jpg",
    description:
      "In the Deep South of 1937, three escaped convicts search for hidden treasure while being pursued by a determined sheriff.",
  },
  {
    id: 177,
    title: "Inside Out",
    director: "Pete Docter",
    authors: ["Pete Docter", "Meg LeFauve"],
    year: 2015,
    genre: ["Animation", "Adventure", "Comedy"],
    rating: 8.1,
    duration: 95,
    language: "English",
    image: "https://image.tmdb.org/t/p/w500/2H1TmgdfNtsKlU9jKdeNyYL5y8T.jpg",
    description:
      "After young Riley is uprooted from her Midwest life and moved to San Francisco, her emotions—Joy, Fear, Anger, Disgust and Sadness—conflict.",
  },
  {
    id: 178,
    title: "Up",
    director: "Pete Docter",
    authors: ["Pete Docter", "Bob Peterson"],
    year: 2009,
    genre: ["Animation", "Adventure", "Comedy"],
    rating: 8.3,
    duration: 96,
    language: "English",
    image: "https://image.tmdb.org/t/p/w500/aUExbt7G7GV8gGHMR3X0QKn0FNZ.jpg",
    description:
      "78-year-old Carl Fredricksen ties thousands of balloons to his house and flies away to fulfill his lifelong dream to explore South America.",
  },
  {
    id: 179,
    title: "Finding Nemo",
    director: "Andrew Stanton",
    authors: ["Andrew Stanton", "Bob Peterson"],
    year: 2003,
    genre: ["Animation", "Adventure", "Comedy"],
    rating: 8.2,
    duration: 100,
    language: "English",
    image: "https://image.tmdb.org/t/p/w500/2diDfBGpMbhOhtVPuKREgOWPQuM.jpg",
    description:
      "After his son is taken by a diver, an overprotective clownfish sets out on a journey across the ocean to bring him back.",
  },
  {
    id: 180,
    title: "The Incredibles",
    director: "Brad Bird",
    authors: ["Brad Bird"],
    year: 2004,
    genre: ["Animation", "Action", "Adventure"],
    rating: 8.0,
    duration: 115,
    language: "English",
    image: "https://image.tmdb.org/t/p/w500/2LqaLgk4Z226KkgPJuiOQ58ShpS.jpg",
    description:
      "A family of undercover superheroes is forced to save the world from a super-villain who wants to destroy it.",
  },
  {
    id: 181,
    title: "Ratatouille",
    director: "Brad Bird",
    authors: ["Brad Bird", "Jan Pinkava"],
    year: 2007,
    genre: ["Animation", "Comedy", "Family"],
    rating: 8.1,
    duration: 111,
    language: "English",
    image: "https://image.tmdb.org/t/p/w500/npHNjldbeTHdKKw28bJKs7lzqzj.jpg",
    description:
      "A rat who can cook makes an unlikely alliance with a young kitchen worker at a famous Paris restaurant.",
  },
  {
    id: 182,
    title: "Shrek",
    director: "Andrew Adamson",
    authors: ["William Steig", "Ted Elliott"],
    year: 2001,
    genre: ["Animation", "Adventure", "Comedy"],
    rating: 7.9,
    duration: 90,
    language: "English",
    image: "https://image.tmdb.org/t/p/w500/iB64vpL3dIObXwtAt0k3gHFWwQg.jpg",
    description:
      "A mean lord exiles fairytale creatures to the swamp of a grumpy ogre, who must go on a quest and rescue a princess for the lord in order to get his land back.",
  },
  {
    id: 183,
    title: "Brave",
    director: "Mark Andrews",
    authors: ["Mark Andrews", "Brenda Chapman"],
    year: 2012,
    genre: ["Animation", "Action", "Adventure"],
    rating: 7.1,
    duration: 93,
    language: "English",
    image: "https://image.tmdb.org/t/p/w500/4MFKEuWJFKb05HiCxCPRB1kIDmM.jpg",
    description:
      "Determined to make her own path in life, a Scottish princess challenges a tradition that brings chaos to her kingdom.",
  },
  {
    id: 184,
    title: "Moana",
    director: "Ron Clements",
    authors: ["Jared Bush", "Ron Clements"],
    year: 2016,
    genre: ["Animation", "Adventure", "Comedy"],
    rating: 7.6,
    duration: 107,
    language: "English",
    image: "https://image.tmdb.org/t/p/w500/xoP3pFCLFbJ3BHXOX5lYDa8ABXS.jpg",
    description:
      "In Ancient Polynesia, when a terrible curse incurred by the Demigod Maui reaches Moana's island, she answers the ocean's call to seek out the demigod to set things right.",
  },
  {
    id: 185,
    title: "Paddington 2",
    director: "Paul King",
    authors: ["Paul King", "Simon Farnaby"],
    year: 2017,
    genre: ["Adventure", "Comedy", "Family"],
    rating: 7.8,
    duration: 103,
    language: "English",
    image: "https://image.tmdb.org/t/p/w500/qkfxnXNSp0W6nnnmB5CsBSIpgAk.jpg",
    description:
      "Paddington Bear, now happily settled with the Brown family, picks up a series of odd jobs to buy a special gift, but the coveted pop-up book is stolen.",
  },
  {
    id: 186,
    title: "The Princess Bride",
    director: "Rob Reiner",
    authors: ["William Goldman"],
    year: 1987,
    genre: ["Adventure", "Comedy", "Fantasy"],
    rating: 8.1,
    duration: 98,
    language: "English",
    image: "https://image.tmdb.org/t/p/w500/gpTkSGF0iJhL4dDcqoE8hs5X7BK.jpg",
    description:
      "A bedridden boy's grandfather reads him the story of a farmboy-turned-pirate who encounters numerous obstacles, enemies and allies in his quest to be reunited with his true love.",
  },
  {
    id: 187,
    title: "Groundhog Day",
    director: "Harold Ramis",
    authors: ["Danny Rubin", "Harold Ramis"],
    year: 1993,
    genre: ["Comedy", "Drama", "Fantasy"],
    rating: 8.0,
    duration: 101,
    language: "English",
    image: "https://image.tmdb.org/t/p/w500/gSiTPpnjEv5q2oEpnGMFOQJBsYO.jpg",
    description:
      "A weatherman finds himself inexplicably living the same day over and over again in Punxsutawney, Pennsylvania.",
  },
  {
    id: 188,
    title: "Office Space",
    director: "Mike Judge",
    authors: ["Mike Judge"],
    year: 1999,
    genre: ["Comedy"],
    rating: 7.7,
    duration: 89,
    language: "English",
    image: "https://image.tmdb.org/t/p/w500/vEt6lxHj3s4bMHOEMCEiPiHpYFX.jpg",
    description:
      "Three company workers who hate their jobs devise a plan to embezzle money from their employer using a computer virus.",
  },
  {
    id: 189,
    title: "The Big Lebowski",
    director: "Joel Coen",
    authors: ["Ethan Coen", "Joel Coen"],
    year: 1998,
    genre: ["Comedy", "Crime"],
    rating: 8.1,
    duration: 117,
    language: "English",
    image: "https://image.tmdb.org/t/p/w500/d3iJlAi2RwKNqeAYQSHnXsWNmTT.jpg",
    description:
      "Slacker Jeff Lebowski, mistaken for a millionaire of the same name, seeks restitution for his ruined rug and enlists his bowling buddies.",
  },
  {
    id: 190,
    title: "Adaptation",
    director: "Spike Jonze",
    authors: ["Susan Orlean", "Charlie Kaufman"],
    year: 2002,
    genre: ["Comedy", "Drama", "Romance"],
    rating: 7.7,
    duration: 115,
    language: "English",
    image: "https://image.tmdb.org/t/p/w500/7jbMyCKiDDaEMpQ2DUVhFSQdU7D.jpg",
    description:
      "A neurotic screenwriter attempts to adapt a book about flowers, becoming increasingly meta about the process of writing itself.",
  },
  {
    id: 191,
    title: "Being John Malkovich",
    director: "Spike Jonze",
    authors: ["Charlie Kaufman"],
    year: 1999,
    genre: ["Comedy", "Drama", "Fantasy"],
    rating: 7.8,
    duration: 112,
    language: "English",
    image: "https://image.tmdb.org/t/p/w500/7LziRinNSJhEQQW4rV7aTUfCZRP.jpg",
    description:
      "A puppeteer discovers a portal that leads literally into the head of movie star John Malkovich.",
  },
  {
    id: 192,
    title: "Synecdoche, New York",
    director: "Charlie Kaufman",
    authors: ["Charlie Kaufman"],
    year: 2008,
    genre: ["Drama"],
    rating: 7.5,
    duration: 124,
    language: "English",
    image: "https://image.tmdb.org/t/p/w500/vbpFibHVaaNlQhlfDNfcPfV2HIO.jpg",
    description:
      "A theater director struggles with his work and various relationships over the course of decades while mounting an ever-expanding theatrical project.",
  },
  {
    id: 193,
    title: "Mulholland Drive",
    director: "David Lynch",
    authors: ["David Lynch"],
    year: 2001,
    genre: ["Drama", "Mystery", "Thriller"],
    rating: 7.9,
    duration: 147,
    language: "English",
    image: "https://image.tmdb.org/t/p/w500/vN7tkRNxmFhlJDPn5mBDMTOEzYV.jpg",
    description:
      "After a car wreck on Mulholland Drive renders a woman amnesiac, she and a perky aspiring actress search for clues and answers.",
  },
  {
    id: 194,
    title: "Blue Velvet",
    director: "David Lynch",
    authors: ["David Lynch"],
    year: 1986,
    genre: ["Drama", "Mystery", "Thriller"],
    rating: 7.8,
    duration: 120,
    language: "English",
    image: "https://image.tmdb.org/t/p/w500/hTUSTlDlmfvmWxsO2PHKD9rRHUX.jpg",
    description:
      "The discovery of a severed human ear found in a field leads a young man on an investigation connected to a mysterious and beautiful nightclub singer.",
  },
  {
    id: 195,
    title: "Lost in Translation",
    director: "Sofia Coppola",
    authors: ["Sofia Coppola"],
    year: 2003,
    genre: ["Drama", "Romance"],
    rating: 7.8,
    duration: 102,
    language: "English",
    image: "https://image.tmdb.org/t/p/w500/8GgKKFVJRXFOvwGIhJLnPt2kM7g.jpg",
    description:
      "A faded movie star and a neglected young woman form an unlikely bond after crossing paths in Tokyo.",
  },
  {
    id: 196,
    title: "The Virgin Suicides",
    director: "Sofia Coppola",
    authors: ["Jeffrey Eugenides", "Sofia Coppola"],
    year: 1999,
    genre: ["Drama", "Mystery"],
    rating: 7.2,
    duration: 97,
    language: "English",
    image: "https://image.tmdb.org/t/p/w500/pkKe7lhDn1hnijBc2kE3GZm9bT6.jpg",
    description:
      "A group of male friends become obsessed with a family of five sisters who are sheltered by their strict, repressive parents.",
  },
  {
    id: 197,
    title: "Marriage Story",
    director: "Noah Baumbach",
    authors: ["Noah Baumbach"],
    year: 2019,
    genre: ["Drama", "Romance"],
    rating: 7.9,
    duration: 136,
    language: "English",
    image: "https://image.tmdb.org/t/p/w500/pZekG6xabTmZxjmYw10wN84Hp8d.jpg",
    description:
      "A stage director and his actress wife struggle through a coast-to-coast divorce that pushes them to their personal extremes.",
  },
  {
    id: 198,
    title: "The Squid and the Whale",
    director: "Noah Baumbach",
    authors: ["Noah Baumbach"],
    year: 2005,
    genre: ["Comedy", "Drama"],
    rating: 7.3,
    duration: 81,
    language: "English",
    image: "https://image.tmdb.org/t/p/w500/uJdFEFdBJtTkFKkjqBdewOQePsh.jpg",
    description:
      "Follows two boys dealing with their parents' divorce in 1980s Brooklyn.",
  },
  {
    id: 199,
    title: "Frances Ha",
    director: "Noah Baumbach",
    authors: ["Noah Baumbach", "Greta Gerwig"],
    year: 2012,
    genre: ["Comedy", "Drama", "Romance"],
    rating: 7.4,
    duration: 86,
    language: "English",
    image: "https://image.tmdb.org/t/p/w500/43f9H2WUAY56hAYV2y5cNjSsX3D.jpg",
    description:
      "An aspiring dancer moves to New York City and becomes caught up in a whirlwind of adolescent exuberance, heartbreak, and self-discovery.",
  },
  {
    id: 200,
    title: "Lady Bird",
    director: "Greta Gerwig",
    authors: ["Greta Gerwig"],
    year: 2017,
    genre: ["Comedy", "Drama"],
    rating: 7.4,
    duration: 94,
    language: "English",
    image: "https://image.tmdb.org/t/p/w500/wuMc08IPKEatf9rnMNXvIDxqP4W.jpg",
    description:
      "In Sacramento in 2002, an artistically inclined seventeen-year-old girl comes of age.",
  },
];

const CATEGORY_ORDER = [
  { key: "Action", label: "Action" },
  { key: "Adventure", label: "Adventure" },
  { key: "Sci-Fi", label: "Sci-Fi" },
  { key: "Drama", label: "Drama" },
  { key: "Crime", label: "Crime" },
  { key: "Thriller", label: "Thriller" },
  { key: "Horror", label: "Horror" },
  { key: "Comedy", label: "Comedy" },
  { key: "Romance", label: "Romance" },
  { key: "Animation", label: "Animation" },
  { key: "Biography", label: "Biography" },
  { key: "History", label: "History" },
  { key: "Fantasy", label: "Fantasy" },
  { key: "Mystery", label: "Mystery" },
  { key: "Western", label: "Western" },
  { key: "Music", label: "Music" },
  { key: "Family", label: "Family" },
];

// ⭐ LATEST (πιο πρόσφατες) προσθήκες ταινιών.
// Μέσω χρήσης του [...ALL_MOVIES], γίνεται copy όλος ο πίνακας με τα αντίστοιχα properties όλων των ταινιών, καθώς δεν τροποποιείται ο original πίνακας, διότι δημιουργείται ένα αντίγραφο αυτού του πίνακα.
const LATEST_MOVIES = [...movies]
  .sort((a, b) => b.year - a.year) // Εδώ πραγματοποιείται μία ταξινόμηση από το μεγαλύτερο έτος προς το μικρότερο έτος, εμφανίζοντας τις πιο πρόσφατες ταινίες πρώτα.
  .slice(0, 20); // Εδώ στην ουσία διατηρούνται οι 20 πιο πρόσφατες ταινίες και εμφανίζονται πρώτες.

// 🔥 POPULAR (υψηλότερο rating) ταινιών.
// Εδώ γίνεται πάλι copy ο πίνακας παρακάτω με την αντίστοιχη ταξινόμηση, εμφανίζοντας το υψηλότερο rating για κάθε ταινία πρώτο, διατηρώντας τις 20 καλύτερες ταινίες με το υψηλότερο rating.
const POPULAR_MOVIES = [...movies]
  .sort((a, b) => b.rating - a.rating)
  .slice(0, 20);

// Παρακάτω γίνεται το αντίστοιχο export στο UI, που αφορά το MoviesPage,μέσω δημιουργίας των αντίστοιχων category objects με το label που θα αναπαριστά τον τίτλο και το movies που θα αναπαριστά τον πίνακα (array) από τις ταινίες.
export const CATEGORIES = [
  { label: "Popular", movies: POPULAR_MOVIES },
  { label: "Latest", movies: LATEST_MOVIES },

  // Το CATEGORY_ORDER αφορά έναν array, όπου μέσω της map λαμβάνεται το κάθε στοιχείο, μετατρέπεται σε κάτι άλλο και επιστρέφεται ένας νέος πίνακας (array).
  // Παρακάτω λαμβάνεται απευθείας το key και το label από το object μέσω του destructuring και χρήσης της arrow function, όπου για κάθε κατηγορία δημιουργείται ένα νέο object.
  // Στην ουσία μέσω του spread operator παρακάτω λαμβάνονται όλα τα στοιχεία του πίνακα (array) και μπαίνουν μέσα στο CATEGORY_ORDER, όπου για κάθε κατηγορία ταινίας δημιουργείται ένα object με το όνομα και όλες τις ταινίες που ανήκουν σε αυτή την κατηγορία.
  ...CATEGORY_ORDER.map(({ key, label }) => ({
    label,
    movies: movies.filter((m) => m.genre.includes(key)), // Μέσω του filter διατρέχω όλες τις ταινίες και διατηρώ μόνο όσες ταινίες ικανοποιούν την συνθήκη, διότι για κάθε ταινία (m),διατηρείται το αντίστοιχο είδος ταινίας, αφού εάν στην θέση του key υπάρχει αυτό εδώ (m.genre === "Action"), τότε το key στην ουσία αντικαθίσταται με το "Action", όπου διατηρούνται μόνο οι Action ταινίες.
  })),
];
